// ============================================================
// WORLD CUP 2026 HOST CITY DATA
// Coordinates + stadiums are accurate — fill in the city info
// (population, teams, attractions) for the remaining cities
// ============================================================

const CITY_DATA = {
  'New York': {
    stadium: 'MetLife Stadium',
    capacity: 78576,
    country: 'USA',
    flag: 'us',
    coordinates: [-74.0742, 40.8128],
    hosts: 'Final 🏆',
    population: '8.3 million',
    founded: 1624,
    funFact: 'The most populous city in the United States.',
    teams: ['New York Giants (NFL)', 'New York Jets (NFL)', 'Yankees (MLB)', 'Knicks (NBA)'],
    attractions: ['Statue of Liberty', 'Times Square'],
  },

  'Mexico City': {
    stadium: 'Estadio Azteca',
    capacity: 87523,
    country: 'Mexico',
    flag: 'mx',
    coordinates: [-99.1505, 19.3029],
    hosts: 'Opening Match ⚽',
    population: '9.2 million',
    founded: 1325,
    funFact: 'First stadium ever to host three different World Cups (1970, 1986, 2026).',
    teams: ['Club América', 'Cruz Azul', 'Mexico National Team'],
    attractions: ['Zócalo', 'Teotihuacan Pyramids'],
  },

  
  'Los Angeles': {
    stadium: 'SoFi Stadium',
    capacity: 70000,
    country: 'USA',
    flag: 'us',
    coordinates: [-118.3392, 33.9535],
    hosts: 'Group Stage + Knockouts',
    population: '3.87 Million',
    founded: 1781,
    funFact: 'Home to the largest stadium in the United States, Was featured as the main city in the game GTA 5.',
    teams: ['Los Angeles Lakers (NBA)','Los Angeles Rams (NFL)', 'Los Angeles Chargers (NFL)', 'LA Galaxy (MLS)'],
    attractions: ['Griffith Observatory', 'Hollywood Sign', 'Universal Studios Hollywood '],
  },

  'Dallas': {
    stadium: 'AT&T Stadium',
    capacity: 94000,
    country: 'USA',
    flag: 'us',
    coordinates: [-97.0945, 32.7473],
    hosts: 'Semi Final',
    population: '1.34 Million',
    founded: 1841,
    funFact: 'Largest capacity stadium of the tournament.',
    teams: ['Dallas Cowboys (NFL)', 'Dallas Mavericks (NBA)', 'FC Dallas (MLS)'],
    attractions: ['AT&T Stadium', 'Dallas Museum of Art', 'Reunion Tower'],
  },

  'San Francisco Bay Area': {
    stadium: "Levi's Stadium",
    capacity: 68500,
    country: 'USA',
    flag: 'us',
    coordinates: [-121.9700, 37.4030],
    hosts: 'Group Stage + Knockouts',
    population: '840K',
    founded: 1776,
    funFact: 'Before it was named San Frabcisco, the city was called Yerba Buena which is Good Herb in Spanish.',
    teams: ['Golden State Warrioirs (NBA)', 'San Francisco 49ers (NFL)', 'San Jose Earthquakes (MLS)'],
    attractions: ['The Golden Gate Bridge', 'Alcatraz Island', 'Fisherman’s Wharf'],
  },

  'Miami': {
    stadium: 'Hard Rock Stadium',
    capacity: 65326,
    country: 'USA',
    flag: 'us',
    coordinates: [-80.2389, 25.9580],
    hosts: '3rd Place Match 🥉',
    population: '500K',
    founded: 1896,
    funFact: 'Miami is the only city in the world that has hosted the Super Bowl, World Series, NBA Finals, and FIFA World Cup.',
    teams: ['Miami Heat (NBA)', 'Miami Dolphins (NFL)', 'Inter Miami CF (MLS)'],
    attractions: ['Miami Beach', 'Wynwood Walls', 'Little Havana'],
  },

  'Atlanta': {
    stadium: 'Mercedes-Benz Stadium',
    capacity: 71000,
    country: 'USA',
    flag: 'us',
    coordinates: [-84.4006, 33.7553],
    hosts: 'Semi Final',
    population: '530K',
    founded: 1837,
    funFact: 'Atlanta is famous for its confusing grid system because it has over 70 streets that share the name "Peachtree"',
    teams: ['Atlanta Falcons (NFL)', 'Atlanta Hawks (NBA)', 'Atlanta United FC (MLS)'],
    attractions: ['Georgia Aquarium', 'World of Coca-Cola', 'Atlanta Botanical Garden'],
  },

  'Seattle': {
    stadium: 'Lumen Field',
    capacity: 69000,
    country: 'USA',
    flag: 'us',
    coordinates: [-122.3316, 47.5952],
    hosts: 'Group Stage + Knockouts',
    population: '785K',
    founded: 1851,
    funFact: 'One of the loudest stadiums in the world.',
    teams: ['Seattle Seahawks (NFL)', 'Seattle Mariners (MLB)', 'Seattle Sounders FC (MLS)'],
    attractions: ['Space Needle', 'Pike Place Market', 'Chihuly Garden and Glass'],
  },

  'Houston': {
    stadium: 'NRG Stadium',
    capacity: 72220,
    country: 'USA',
    flag: 'us',
    coordinates: [-95.4107, 29.6847],
    hosts: 'Group Stage + Knockouts',
    population: '2.4 Million',
    founded: 1836,
    funFact: 'Houston is considered the most ethnically diverse metropolitain area in the United States.',
    teams: ['Houston Astros (MLB)', 'Houston Texans (NFL)'],
    attractions: ['Space Center Houston', 'Houston Museum of Fine Arts', 'Discovery Green'],
  },

  'Boston': {
    stadium: 'Gillette Stadium',
    capacity: 65878,
    country: 'USA',
    flag: 'us',
    coordinates: [-71.2643, 42.0909],
    hosts: 'Group Stage + Knockouts',
    population: '673K',
    founded: 1630,
    funFact: 'Boston is home to the first public beach in the United States, Revere Beach, which opened in 1896, and also the first public library.',
    teams: ['Boston Red Sox (MLB)', 'New England Patriots (NFL)', 'Boston Celtics (NBA)', 'Boston Bruins (NHL)'],
    attractions: ['Freedom Trail', 'Fenway Park', 'Museum of Fine Arts'],
  },

  'Philadelphia': {
    stadium: 'Lincoln Financial Field',
    capacity: 69596,
    country: 'USA',
    flag: 'us',
    coordinates: [-75.1675, 39.9008],
    hosts: 'Group Stage + Knockouts',
    population: '1.6M',
    founded: 1790,
    funFact: 'Philadelphia was once the capital of the United States from 1790 to 1800 temporarily, while Washington DC was being served.',
    teams: ['Philadelphia Eagles (NFL)', 'Philadelphia Phillies (MLB)', 'Philadelphia 76ers (NBA)', 'Philadelphia Flyers (NHL)'],
    attractions: ['Liberty Bell', 'Independence Hall', 'Philadelphia Museum of Art'],
  },

  'Kansas City': {
    stadium: 'Arrowhead Stadium',
    capacity: 76416,
    country: 'USA',
    flag: 'us',
    coordinates: [-94.4839, 39.0489],
    hosts: 'Quarter Final',
    population: '2.27 Million',
    founded: 1855,
    funFact: 'Kansas City is known for its vibrant arts scene and is home to the renowned Kauffman Center for the Performing Arts.',
    teams: ['Kansas City Chiefs (NFL)', 'Kansas City Royals (MLB)', 'Sporting Kansas City (MLS)'],
    attractions: ['National World War I Museum and Memorial', 'Kauffman Center for the Performing Arts', 'Westport Cultural District'],
  },

  'Guadalajara': {
    stadium: 'Estadio Akron',
    capacity: 48071,
    country: 'Mexico',
    flag: 'mx',
    coordinates: [-103.4625, 20.6819],
    hosts: 'Group Stage',
    population: '1.6M',
    founded: 1541,
    funFact: 'The city is known as the birthplace of mariachi music and is famous for its vibrant culture and rich history.',
    teams: ['C.D.A Guadalajara (Liga MX)'],
    attractions: ['Centro Histórico', 'Hospicio Cabañas', 'Tlaquepaque and Tonalá'],
  },

  'Monterrey': {
    stadium: 'Estadio BBVA',
    capacity: 53500,
    country: 'Mexico',
    flag: 'mx',
    coordinates: [-100.2444, 25.6694],
    hosts: 'Group Stage + Round of 32',
    population: '1.1M',
    founded: 1841,
    funFact: 'The Paseo Santa Lucía is considered one of the longest artificial, navigable rivers in Latin America.',
    teams: ['C.F. Monterrey (Liga MX)', 'Tigres UANL (Liga MX)'],
    attractions: ['Macroplaza', 'Fundidora Park', 'Santa Lucia Riverwalk'],
  },

  'Toronto': {
    stadium: 'BMO Field',
    capacity: 45000,
    country: 'Canada',
    flag: 'ca',
    coordinates: [-79.4185, 43.6332],
    hosts: 'Group Stage + Round of 32',
    population: '3M',
    founded: 1793,
    funFact: 'Toronto is the largest city in Canada and is known for its multicultural population, with over 50% of its residents being born outside of Canada.',
    teams: ['Toronto FC (MLS)', 'Toronto Raptors (NBA)', 'Toronto Maple Leafs (NHL)'],
    attractions: ['CN Tower', 'Royal Ontario Museum', 'Toronto Islands'],
  },

  'Vancouver': {
    stadium: 'BC Place',
    capacity: 54500,
    country: 'Canada',
    flag: 'ca',
    coordinates: [-123.1119, 49.2768],
    hosts: 'Group Stage + Round of 32',
    population: '631K',
    founded: 1886,
    funFact: 'Vancouver is known for its beautiful natural surroundings and is home to several world-class museums and galleries.',
    teams: ['Vancouver Whitecaps FC (MLS)'],
    attractions: ['Stanely Park', 'Granville Island', 'Capilano Suspension Bridge Park'],
  },
}

export default CITY_DATA