// ============================================================
// COUNTRY DATA — World Cup history, stats and records
// Sources: Wikipedia, FIFA.com
// ============================================================

const COUNTRY_DATA = {

  'Brazil': {
    flag: 'br',
    confederation: 'CONMEBOL',
    fifa_ranking: 5,
    coach: 'Carlo Ancelotti',
    captain: 'Marquinhos',
    all_time_appearances: 22,
    titles: 5,
    title_years: [1958, 1962, 1970, 1994, 2002],
    best_result: '🏆 5x World Cup Champions',
    total_matches: 114,
    total_wins: 76,
    total_draws: 18,
    total_losses: 20,
    goals_scored: 237,
    goals_conceded: 101,
    top_scorer: { name: 'Ronaldo', goals: 15 },
    most_capped: { name: 'Cafu', caps: 142 },
    biggest_win: '7-1 vs Germany (2014 SF) — but as hosts losing',
    group_2026: 'C',
    history: [
      { year: 1930, result: 'Semi Finals' },
      { year: 1934, result: 'Round of 16' },
      { year: 1938, result: 'Semi Finals' },
      { year: 1950, result: 'Runners Up' },
      { year: 1954, result: 'Quarter Finals' },
      { year: 1958, result: '🏆 Champions' },
      { year: 1962, result: '🏆 Champions' },
      { year: 1966, result: 'Group Stage' },
      { year: 1970, result: '🏆 Champions' },
      { year: 1974, result: '4th Place' },
      { year: 1978, result: '3rd Place' },
      { year: 1982, result: 'Round of 16' },
      { year: 1986, result: 'Quarter Finals' },
      { year: 1990, result: 'Round of 16' },
      { year: 1994, result: '🏆 Champions' },
      { year: 1998, result: 'Runners Up' },
      { year: 2002, result: '🏆 Champions' },
      { year: 2006, result: 'Quarter Finals' },
      { year: 2010, result: 'Quarter Finals' },
      { year: 2014, result: '4th Place' },
      { year: 2018, result: 'Quarter Finals' },
      { year: 2022, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'France': {
    flag: 'fr',
    confederation: 'UEFA',
    fifa_ranking: 2,
    coach: 'Didier Deschamps',
    captain: 'Kylian Mbappé',
    all_time_appearances: 16,
    titles: 2,
    title_years: [1998, 2018],
    best_result: '🏆 2x World Cup Champions',
    total_matches: 66,
    total_wins: 38,
    total_draws: 13,
    total_losses: 15,
    goals_scored: 120,
    goals_conceded: 68,
    top_scorer: { name: 'Just Fontaine', goals: 13 },
    most_capped: { name: 'Hugo Lloris', caps: 145 },
    biggest_win: '10-0 vs Azerbaijan (2021 WCQ)',
    group_2026: 'I',
    history: [
      { year: 1930, result: 'Group Stage' },
      { year: 1934, result: 'Round of 16' },
      { year: 1938, result: 'Quarter Finals' },
      { year: 1954, result: 'Group Stage' },
      { year: 1958, result: '3rd Place' },
      { year: 1966, result: 'Group Stage' },
      { year: 1978, result: 'Group Stage' },
      { year: 1982, result: '4th Place' },
      { year: 1986, result: '3rd Place' },
      { year: 1998, result: '🏆 Champions' },
      { year: 2002, result: 'Group Stage' },
      { year: 2006, result: 'Runners Up' },
      { year: 2010, result: 'Group Stage' },
      { year: 2014, result: 'Quarter Finals' },
      { year: 2018, result: '🏆 Champions' },
      { year: 2022, result: 'Runners Up' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Argentina': {
    flag: 'ar',
    confederation: 'CONMEBOL',
    fifa_ranking: 1,
    coach: 'Lionel Scaloni',
    captain: 'Lionel Messi',
    all_time_appearances: 19,
    titles: 3,
    title_years: [1978, 1986, 2022],
    best_result: '🏆 3x World Cup Champions',
    total_matches: 88,
    total_wins: 47,
    total_draws: 15,
    total_losses: 26,
    goals_scored: 145,
    goals_conceded: 97,
    top_scorer: { name: 'Gabriel Batistuta', goals: 10 },
    most_capped: { name: 'Lionel Messi', caps: 191 },
    biggest_win: '6-0 vs Serbia & Montenegro (2006)',
    group_2026: 'J',
    history: [
      { year: 1930, result: 'Runners Up' },
      { year: 1934, result: 'Round of 16' },
      { year: 1958, result: 'Group Stage' },
      { year: 1962, result: 'Group Stage' },
      { year: 1966, result: 'Quarter Finals' },
      { year: 1974, result: 'Round of 16' },
      { year: 1978, result: '🏆 Champions' },
      { year: 1982, result: 'Round of 16' },
      { year: 1986, result: '🏆 Champions' },
      { year: 1990, result: 'Runners Up' },
      { year: 1994, result: 'Round of 16' },
      { year: 1998, result: 'Quarter Finals' },
      { year: 2002, result: 'Group Stage' },
      { year: 2006, result: 'Quarter Finals' },
      { year: 2010, result: 'Quarter Finals' },
      { year: 2014, result: 'Runners Up' },
      { year: 2018, result: 'Round of 16' },
      { year: 2022, result: '🏆 Champions' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'England': {
    flag: 'gb-eng',
    confederation: 'UEFA',
    fifa_ranking: 4,
    coach: 'Thomas Tuchel',
    captain: 'Harry Kane',
    all_time_appearances: 16,
    titles: 1,
    title_years: [1966],
    best_result: '🏆 1966 World Cup Champions',
    total_matches: 69,
    total_wins: 33,
    total_draws: 21,
    total_losses: 15,
    goals_scored: 100,
    goals_conceded: 60,
    top_scorer: { name: 'Harry Kane', goals: 68 },
    most_capped: { name: 'Peter Shilton', caps: 125 },
    biggest_win: '8-0 vs Mexico (1961 friendly)',
    group_2026: 'L',
    history: [
      { year: 1950, result: 'Group Stage' },
      { year: 1954, result: 'Quarter Finals' },
      { year: 1958, result: 'Group Stage' },
      { year: 1962, result: 'Quarter Finals' },
      { year: 1966, result: '🏆 Champions' },
      { year: 1970, result: 'Quarter Finals' },
      { year: 1982, result: 'Round of 16' },
      { year: 1986, result: 'Quarter Finals' },
      { year: 1990, result: '4th Place' },
      { year: 1998, result: 'Round of 16' },
      { year: 2002, result: 'Quarter Finals' },
      { year: 2006, result: 'Quarter Finals' },
      { year: 2010, result: 'Round of 16' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: '4th Place' },
      { year: 2022, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Spain': {
    flag: 'es',
    confederation: 'UEFA',
    fifa_ranking: 3,
    coach: 'Luis de la Fuente',
    captain: 'Álvaro Morata',
    all_time_appearances: 16,
    titles: 1,
    title_years: [2010],
    best_result: '🏆 2010 World Cup Champions',
    total_matches: 67,
    total_wins: 34,
    total_draws: 16,
    total_losses: 17,
    goals_scored: 110,
    goals_conceded: 72,
    top_scorer: { name: 'David Villa', goals: 59 },
    most_capped: { name: 'Sergio Ramos', caps: 180 },
    biggest_win: '7-0 vs Costa Rica (2022)',
    group_2026: 'H',
    history: [
      { year: 1934, result: 'Quarter Finals' },
      { year: 1950, result: '4th Place' },
      { year: 1962, result: 'Group Stage' },
      { year: 1966, result: 'Group Stage' },
      { year: 1978, result: 'Round of 16' },
      { year: 1982, result: 'Round of 16' },
      { year: 1986, result: 'Quarter Finals' },
      { year: 1990, result: 'Round of 16' },
      { year: 1994, result: 'Quarter Finals' },
      { year: 1998, result: 'Round of 16' },
      { year: 2002, result: 'Quarter Finals' },
      { year: 2006, result: 'Round of 16' },
      { year: 2010, result: '🏆 Champions' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: 'Round of 16' },
      { year: 2022, result: 'Round of 16' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Germany': {
    flag: 'de',
    confederation: 'UEFA',
    fifa_ranking: 12,
    coach: 'Julian Nagelsmann',
    captain: 'Joshua Kimmich',
    all_time_appearances: 20,
    titles: 4,
    title_years: [1954, 1974, 1990, 2014],
    best_result: '🏆 4x World Cup Champions',
    total_matches: 109,
    total_wins: 67,
    total_draws: 20,
    total_losses: 22,
    goals_scored: 226,
    goals_conceded: 125,
    top_scorer: { name: 'Miroslav Klose', goals: 16 },
    most_capped: { name: 'Lothar Matthäus', caps: 150 },
    biggest_win: '8-0 vs Saudi Arabia (2002)',
    group_2026: 'E',
    history: [
      { year: 1934, result: '3rd Place' },
      { year: 1938, result: 'Round of 16' },
      { year: 1954, result: '🏆 Champions' },
      { year: 1958, result: '4th Place' },
      { year: 1962, result: 'Quarter Finals' },
      { year: 1966, result: 'Runners Up' },
      { year: 1970, result: '3rd Place' },
      { year: 1974, result: '🏆 Champions' },
      { year: 1978, result: 'Round of 16' },
      { year: 1982, result: 'Runners Up' },
      { year: 1986, result: 'Runners Up' },
      { year: 1990, result: '🏆 Champions' },
      { year: 1994, result: 'Quarter Finals' },
      { year: 1998, result: 'Quarter Finals' },
      { year: 2002, result: 'Runners Up' },
      { year: 2006, result: '3rd Place' },
      { year: 2010, result: '3rd Place' },
      { year: 2014, result: '🏆 Champions' },
      { year: 2018, result: 'Group Stage' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Portugal': {
    flag: 'pt',
    confederation: 'UEFA',
    fifa_ranking: 6,
    coach: 'Roberto Martínez',
    captain: 'Cristiano Ronaldo',
    all_time_appearances: 9,
    titles: 0,
    title_years: [],
    best_result: '3rd Place (1966)',
    total_matches: 37,
    total_wins: 18,
    total_draws: 8,
    total_losses: 11,
    goals_scored: 63,
    goals_conceded: 43,
    top_scorer: { name: 'Cristiano Ronaldo', goals: 143 },
    most_capped: { name: 'Cristiano Ronaldo', caps: 226 },
    biggest_win: '7-0 vs North Korea (2010)',
    group_2026: 'K',
    history: [
      { year: 1966, result: '3rd Place' },
      { year: 1986, result: 'Round of 16' },
      { year: 2002, result: 'Group Stage' },
      { year: 2006, result: '4th Place' },
      { year: 2010, result: 'Round of 16' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: 'Round of 16' },
      { year: 2022, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Netherlands': {
    flag: 'nl',
    confederation: 'UEFA',
    fifa_ranking: 7,
    coach: 'Ronald Koeman',
    captain: 'Virgil van Dijk',
    all_time_appearances: 11,
    titles: 0,
    title_years: [],
    best_result: 'Runners Up (1974, 1978, 2010)',
    total_matches: 52,
    total_wins: 29,
    total_draws: 10,
    total_losses: 13,
    goals_scored: 99,
    goals_conceded: 57,
    top_scorer: { name: 'Robin van Persie', goals: 50 },
    most_capped: { name: 'Wesley Sneijder', caps: 134 },
    biggest_win: '7-0 vs Spain (2014)',
    group_2026: 'F',
    history: [
      { year: 1934, result: 'Round of 16' },
      { year: 1938, result: 'Round of 16' },
      { year: 1974, result: 'Runners Up' },
      { year: 1978, result: 'Runners Up' },
      { year: 1990, result: 'Round of 16' },
      { year: 1994, result: 'Quarter Finals' },
      { year: 1998, result: '4th Place' },
      { year: 2006, result: 'Round of 16' },
      { year: 2010, result: 'Runners Up' },
      { year: 2014, result: '3rd Place' },
      { year: 2022, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },
  'Australia': {
    flag: 'au',
    confederation: 'AFC',
    fifa_ranking: 7,
    coach: 'Tony Popovic',
    captain: 'Mark Schwarzer',
    all_time_appearances: 7,
    titles: 0,
    title_years: [],
    best_result: 'Round of 16 (2006, 2022)',
    total_matches: 20,
    total_wins: 4,
    total_draws: 4,
    total_losses: 12,
    goals_scored: 13,
    goals_conceded: 32,
    top_scorer: { name: 'Tim Cahill', goals: 5 },
    most_capped: { name: 'Mathew Leckie and Mathew Ryan', caps: 10 },
    biggest_win: '3-1 vs Japan (2006)',
    group_2026: 'D',
    history: [
      { year: 1974, result: 'Group Stage' },
      { year: 2006, result: 'Round of 16' },
      { year: 2010, result: 'Group Stage' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: 'Group Stage' },
      { year: 2022, result: 'Round of 16' },
      { year: 2026, result: 'TBD' },
    ]
  },
  'Austria': {
    flag: 'at',
    confederation: 'UEFA',
    fifa_ranking: 22,
    coach: 'Ralf Rangnick',
    captain: 'David Alaba',
    all_time_appearances: 8,
    titles: 0,
    title_years: [],
    total_matches: 29,
    total_wins: 12,
    total_draws: 4,
    total_losses: 13,
    goals_scored: 43,
    goals_conceded: 47,
    best_result: 'Third Place',
    top_scorer: { name: 'Erich Prost', goals: 6 },
    most_capped: { name: 'Fredrick Koncilla, Erich Obermayer, Bruno Pezzey, Herbert Prohaska', caps: 11 },
    biggest_win: '5-0 vs Czechoslovakia (1954)',
    group_2026: 'J',
    history: [
      { year: 1934, result: '4th Place' },
      { year: 1954, result: '3rd Place' },
      { year: 1958, result: 'Group Stage' },
      { year: 1978, result: 'Second Group Stage' },
      { year: 1982, result: 'Second Group Stage' },
      { year: 1990, result: 'Group Stage' },
      { year: 1998, result: 'Group Stage' },
      { year: 2026, result: 'TBD' }
    ]
  },
  'Belgium': {
    flag: 'be',
    confederation: 'UEFA',
    fifa_ranking: 8,
    coach: 'Rudi Garcia',
    captain: 'Kevin De Bruyne',
    all_time_appearances: 15,
    titles: 0,
    title_years: [],
    total_matches: 49,
    total_wins: 27,
    total_draws: 10,
    total_losses: 12,
    goals_scored: 120,
    goals_conceded: 72,
    top_scorer: { name: 'Marc Wilmots, Romelu Lukaku', goals: 5 },
    most_capped: { name: 'Enzo Scifo', caps: 17 },
    best_result: 'Third Place',
    group_2026: 'G',
    history: [
      { year: 1930, result: 'First Round' },
      { year: 1934, result: 'Round of 16' },
      { year: 1938, result: 'Round of 16' },
      { year: 1954, result: 'Group Stage' },
      { year: 1970, result: 'First Group Stage' },
      { year: 1982, result: 'Second Group Stage' },
      { year: 1986, result: '4th Place' },
      { year: 1990, result: 'Round of 16' },
      { year: 1994, result: 'Round of 16' },
      { year: 1998, result: 'Group Stage' },
      { year: 2002, result: 'Round of 16' },
      { year: 2014, result: 'Quarter Finals' },
      { year: 2018, result: '3rd Place' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' }
    ]
  },
  'Bosnia': {
    flag: 'ba',
    confederation: 'UEFA',
    fifa_ranking: 68,
    coach: 'Sergej Barbarez',
    captain: 'Edin Dzeko',
    all_time_appearances: 2,
    titles: 0,
    title_years: [],
    total_matches: 3,
    total_wins: 0,
    total_draws: 1,
    total_losses: 2,
    goals_scored: 2,
    goals_conceded: 7,
    top_scorer: { name: 'Edin Dzeko', goals: 2 },
    most_capped: { name: 'Edin Dzeko', caps: 3 },
    best_result: 'Group Stage',
    group_2026: 'B',
    history: [
      { year: 2014, result: 'Group Stage' },
      { year: 2026, result: 'TBD' }
    ]
  },
  'Canada': {
    flag: 'ca',
    confederation: 'CONCACAF',
    fifa_ranking: 31,
    coach: 'Jesse Marsch',
    captain: 'Alphonso Davies',
    all_time_appearances: 3,
    titles: 0,
    title_years: [],
    total_matches: 7,
    total_wins: 0,
    total_draws: 1,
    total_losses: 6,
    goals_scored: 2,
    goals_conceded: 22,
    top_scorer: { name: 'Lucas Cavallini', goals: 2 },
    most_capped: { name: 'Atiba Hutchinson', caps: 8 },
    best_result: 'Group Stage',
    group_2026: 'B',
    history: [
      { year: 1986, result: 'Group Stage' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' }
    ]
  },
  'Colombia': {
    flag: 'co',
    confederation: 'CONMEBOL',
    fifa_ranking: 12,
    coach: 'Nestor Lorenzo',
    captain: 'James Rodriguez',
    all_time_appearances: 7,
    titles: 0,
    title_years: [],
    total_matches: 22,
    total_wins: 9,
    total_draws: 3,
    total_losses: 10,
    goals_scored: 32,
    goals_conceded: 30,
    top_scorer: { name: 'James Rodriguez', goals: 6 },
    most_capped: { name: 'Freddy Rincon, Carlos Valderrama', caps: 10 },
    best_result: 'Quarter Finals',
    group_2026: 'K',
    history: [
      { year: 1962, result: 'Group Stage' },
      { year: 1990, result: 'Round of 16' },
      { year: 1994, result: 'Group Stage' },
      { year: 1998, result: 'Group Stage' },
      { year: 2014, result: 'Quarter Finals' },
      { year: 2018, result: 'Round of 16' },
      { year: 2026, result: 'TBD' }
    ]
  },
  'Croatia': {
    flag: 'hr',
    confederation: 'UEFA',
    fifa_ranking: 10,
    coach: 'Zlatko Dalic',
    captain: 'Luka Modric',
    all_time_appearances: 7,
    titles: 0,
    title_years: [],
    total_matches: 21,
    total_wins: 11,
    total_draws: 4,
    total_losses: 6,
    goals_scored: 34,
    goals_conceded: 22,
    top_scorer: { name: 'Davor Suker', goals: 12 },
    most_capped: { name: 'Luka Modric', caps: 22 },
    best_result: 'Runners Up',
    group_2026: 'L',
    history: [
      { year: 1998, result: '3rd Place' },
      { year: 2002, result: 'Group Stage' },
      { year: 2006, result: 'Group Stage' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: 'Runners Up' },
      { year: 2022, result: '3rd Place' },
      { year: 2026, result: 'TBD' }
    ]
  },
  'Czech Republic': {
    flag: 'cz',
    confederation: 'UEFA',
    fifa_ranking: 36,
    coach: 'Ivan Hasek',
    captain: 'Tomas Soucek',
    all_time_appearances: 10,
    titles: 0,
    title_years: [],
    total_matches: 33,
    total_wins: 12,
    total_draws: 5,
    total_losses: 16,
    goals_scored: 47,
    goals_conceded: 49,
    top_scorer: { name: 'Oldrich Nejedly', goals: 7 },
    most_capped: { name: 'Ladislav Novak', caps: 12 },
    best_result: 'Runners Up',
    group_2026: 'A',
    history: [
      { year: 1934, result: 'Runners Up' },
      { year: 1938, result: 'Quarter Finals' },
      { year: 1954, result: 'Group Stage' },
      { year: 1958, result: 'Group Stage' },
      { year: 1962, result: 'Runners Up' },
      { year: 1970, result: 'Group Stage' },
      { year: 1982, result: 'Quarter Finals' },
      { year: 1990, result: 'Quarter Finals' },
      { year: 2006, result: 'Group Stage' },
      { year: 2026, result: 'TBD' }
    ]
  },
 
  'Egypt': {
    flag: 'eg',
    confederation: 'CAF',
    fifa_ranking: 29,
    coach: 'Hossam Hassan',
    captain: 'Mohamed Salah',
    all_time_appearances: 4,
    titles: 0,
    title_years: [],
    total_matches: 7,
    total_wins: 0,
    total_draws: 2,
    total_losses: 5,
    goals_scored: 5,
    goals_conceded: 12,
    top_scorer: { name: 'Abdelrahman Fawzi, Mohamed Salah', goals: 2 },
    most_capped: { name: 'Magdi Abdelghani, Gamal Abdelhamid, Ahmed El-Kass, Hossam Hassan, Ibrahim Hassan, Hany Ramzy, Ahmed Shobier, Hesham Yakan, Rabie Yassin, Ismail Youssef, Mohammad Abdel Shafy, Mohammad Elneny, Ahmed Fathy, Ali Gabr, Tarek Hamed, Ahmed Hegazi, Kahraba, Marwan Mohsen, Abdallah El-Sayed, Ramadan Sobhi, Trezeguet', caps: 3 },
    best_result: 'Group Stage',
    group_2026: 'G',
    history: [
      { year: 1934, result: 'Round of 16' },
      { year: 1990, result: 'Group Stage' },
      { year: 2018, result: 'Group Stage' },
      { year: 2026, result: 'TBD' }
    ]
  },

  'DR Congo': {
    flag: 'cd',
    confederation: 'CAF',
    fifa_ranking: 61,
    coach: 'Sebastien Desabre',
    captain: 'Chancel Mbemba',
    all_time_appearances: 2, 
    titles: 0,
    title_years: [],
    total_matches: 3,
    total_wins: 0,
    total_draws: 0,
    total_losses: 3,
    goals_scored: 0,
    goals_conceded: 14,
    top_scorer: { name: 'none', goals: 0 },
    most_capped: { name: 'Tshimen Bwanga, Mwepu IIunga, Mwamba Kazadi, Mantantu Kidumu, Massamba Kilasu, Boba Lobilo, Mambwene Mana, Adelard Mayanga Maku, Mwanza Mukombo, Kembo Uba Kembo', caps: 3 },
    best_result: 'Group Stage',
    group_2026: 'K',
    history: [
      { year: 1974, result: 'Group Stage' },
      { year: 2026, result: 'TBD' }
    ]
  },

   'Uruguay': {
    flag: 'uy',
    confederation: 'CONMEBOL',
    fifa_ranking: 14,
    coach: 'Marcelo Bielsa',
    captain: 'Federico Valverde',
    all_time_appearances: 15,
    titles: 2,
    title_years: [1930, 1950],
    total_matches: 59,
    total_wins: 25,
    total_draws: 13,
    total_losses: 21,
    goals_scored: 89,
    goals_conceded: 76,
    best_result: 'Champions (1930, 1950)',
    top_scorer: { name: 'Oscar Miguez', goals: 8 },
    most_capped: { name: 'Edinson Cavani', caps: 17 },
    group_2026: 'H',
    history: [
      { year: 1930, result: 'Champions' },
      { year: 1950, result: 'Champions' },
      { year: 1954, result: '4th Place' },
      { year: 1962, result: 'Group Stage' },
      { year: 1966, result: 'Quarter Finals' },
      { year: 1970, result: 'Fourth Place' },
      { year: 1974, result: 'Group Stage' },
      { year: 1986, result: 'Round of 16' },
      { year: 1990, result: 'Round of 16' },
      { year: 2002, result: 'Group Stage' },
      { year: 2010, result: '4th Place' },
      { year: 2014, result: 'Round of 16' },
      { year: 2018, result: 'Quarter Finals' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' }
    ]
  },

   'USA': {
    flag: 'us',
    confederation: 'CONCACAF',
    fifa_ranking: 16,
    coach: 'Mauricio Pochettino',
    captain: 'Christian Pulisic',
    all_time_appearances: 12,
    titles: 0,
    title_years: [],
    total_matches: 37,
    total_wins: 9,
    total_draws: 8,
    total_losses: 20,
    goals_scored: 40,
    goals_conceded: 66,
    best_result: 'Third Place (1930)',
    top_scorer: { name: 'Landon Donovan', goals: 5 },
    most_capped: { name: 'Landon Donovan', caps: 12 },
    group_2026: 'D',
    history: [
      { year: 1930, result: '3rd Place' },
      { year: 1934, result: 'Round of 16' },
      { year: 1950, result: 'Group Stage' },
      { year: 1990, result: 'Group Stage' },
      { year: 1994, result: 'Round of 16' },
      { year: 1998, result: 'Group Stage' },
      { year: 2002, result: 'Quarter Finals' },
      { year: 2006, result: 'Group Stage' },
      { year: 2010, result: 'Round of 16' },
      { year: 2014, result: 'Round of 16' },
      { year: 2022, result: 'Round of 16' },
      { year: 2026, result: 'TBD' }
    ]
  },

  'Mexico': {
  flag: 'mx',
  confederation: 'CONCACAF',
  fifa_ranking: 17,
  coach: 'Javier Aguirre',
  captain: 'Edson Alvarez',
  all_time_appearances: 18,
  titles: 0,
  title_years: [],
  total_matches: 60,
  total_wins: 17,
  total_draws: 15,
  total_losses: 28,
  goals_scored: 62,
  goals_conceded: 101,
  best_result: 'Quarter Finals (1970, 1986)',
  top_scorer: { name: 'Luis Hernández, Javier Hernández', goals: 4 },
  most_capped: { name: 'Rafael Márquez', caps: 19 },
  group_2026: 'A',
  history: [
    { year: 1930, result: 'Group Stage' },
    { year: 1950, result: 'Group Stage' },
    { year: 1954, result: 'Group Stage' },
    { year: 1958, result: 'Group Stage' },
    { year: 1962, result: 'Group Stage' },
    { year: 1966, result: 'Group Stage' },
    { year: 1970, result: 'Quarter Finals' },
    { year: 1978, result: 'Group Stage' },
    { year: 1986, result: 'Quarter Finals' },
    { year: 1994, result: 'Round of 16' },
    { year: 1998, result: 'Round of 16' },
    { year: 2002, result: 'Round of 16' },
    { year: 2006, result: 'Round of 16' },
    { year: 2010, result: 'Round of 16' },
    { year: 2014, result: 'Round of 16' },
    { year: 2018, result: 'Round of 16' },
    { year: 2022, result: 'Group Stage' },
    { year: 2026, result: 'TBD' }
  ]
},

'South Korea': {
    flag: 'kr',
    confederation: 'AFC',
    fifa_ranking: 23,
    coach: 'Hong Myung-bo',
    captain: 'Son Heung-min',
    all_time_appearances: 11,
    titles: 0,
    title_years: [],
    best_result: 'Semi Finals (2002)',
    total_matches: 35,
    total_wins: 9,
    total_draws: 8,
    total_losses: 18,
    goals_scored: 35,
    goals_conceded: 58,
    top_scorer: { name: 'Ahn Jung-hwan', goals: 3 },
    most_capped: { name: 'Son Heung-min', caps: 13 },
    biggest_win: '3-0 vs Portugal (2002)',
    group_2026: 'A',
    history: [
      { year: 1954, result: 'Group Stage' },
      { year: 1986, result: 'Group Stage' },
      { year: 1990, result: 'Group Stage' },
      { year: 1994, result: 'Group Stage' },
      { year: 1998, result: 'Group Stage' },
      { year: 2002, result: 'Semi Finals' },
      { year: 2006, result: 'Group Stage' },
      { year: 2010, result: 'Round of 16' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: 'Group Stage' },
      { year: 2022, result: 'Round of 16' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'South Africa': {
    flag: 'za',
    confederation: 'CAF',
    fifa_ranking: 67,
    coach: 'Hugo Broos',
    captain: 'Percy Tau',
    all_time_appearances: 3,
    titles: 0,
    title_years: [],
    best_result: 'Group Stage',
    total_matches: 9,
    total_wins: 1,
    total_draws: 3,
    total_losses: 5,
    goals_scored: 9,
    goals_conceded: 17,
    top_scorer: { name: 'Shaun Bartlett', goals: 2 },
    most_capped: { name: 'Aaron Mokoena', caps: 9 },
    biggest_win: '2-1 vs France (2010)',
    group_2026: 'A',
    history: [
      { year: 1998, result: 'Group Stage' },
      { year: 2002, result: 'Group Stage' },
      { year: 2010, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Switzerland': {
    flag: 'ch',
    confederation: 'UEFA',
    fifa_ranking: 20,
    coach: 'Murat Yakin',
    captain: 'Granit Xhaka',
    all_time_appearances: 12,
    titles: 0,
    title_years: [],
    best_result: 'Quarter Finals (1934, 1938, 1954)',
    total_matches: 37,
    total_wins: 12,
    total_draws: 8,
    total_losses: 17,
    goals_scored: 55,
    goals_conceded: 67,
    top_scorer: { name: 'Josef Hugi', goals: 6 },
    most_capped: { name: 'Stephan Lichtsteiner', caps: 12 },
    biggest_win: '5-0 vs Italy (1928)',
    group_2026: 'B',
    history: [
      { year: 1934, result: 'Quarter Finals' },
      { year: 1938, result: 'Quarter Finals' },
      { year: 1950, result: 'Group Stage' },
      { year: 1954, result: 'Quarter Finals' },
      { year: 1962, result: 'Group Stage' },
      { year: 1966, result: 'Group Stage' },
      { year: 1994, result: 'Round of 16' },
      { year: 2006, result: 'Round of 16' },
      { year: 2010, result: 'Group Stage' },
      { year: 2014, result: 'Round of 16' },
      { year: 2018, result: 'Round of 16' },
      { year: 2022, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Qatar': {
    flag: 'qa',
    confederation: 'AFC',
    fifa_ranking: 37,
    coach: 'Marquez Lopez',
    captain: 'Hassan Al-Haydos',
    all_time_appearances: 2,
    titles: 0,
    title_years: [],
    best_result: 'Group Stage',
    total_matches: 6,
    total_wins: 1,
    total_draws: 0,
    total_losses: 5,
    goals_scored: 5,
    goals_conceded: 13,
    top_scorer: { name: 'Akram Afif', goals: 3 },
    most_capped: { name: 'Hassan Al-Haydos', caps: 6 },
    biggest_win: '3-1 vs Senegal (2022)',
    group_2026: 'B',
    history: [
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Scotland': {
    flag: 'gb-sct',
    confederation: 'UEFA',
    fifa_ranking: 39,
    coach: 'Steve Clarke',
    captain: 'Andrew Robertson',
    all_time_appearances: 9,
    titles: 0,
    title_years: [],
    best_result: 'Group Stage',
    total_matches: 23,
    total_wins: 4,
    total_draws: 7,
    total_losses: 12,
    goals_scored: 25,
    goals_conceded: 41,
    top_scorer: { name: 'Joe Jordan', goals: 4 },
    most_capped: { name: 'David Narey', caps: 9 },
    biggest_win: '2-1 vs Zaire (1974)',
    group_2026: 'C',
    history: [
      { year: 1954, result: 'Group Stage' },
      { year: 1958, result: 'Group Stage' },
      { year: 1974, result: 'Group Stage' },
      { year: 1978, result: 'Group Stage' },
      { year: 1982, result: 'Group Stage' },
      { year: 1986, result: 'Group Stage' },
      { year: 1990, result: 'Group Stage' },
      { year: 1998, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Morocco': {
    flag: 'ma',
    confederation: 'CAF',
    fifa_ranking: 14,
    coach: 'Walid Regragui',
    captain: 'Achraf Hakimi',
    all_time_appearances: 7,
    titles: 0,
    title_years: [],
    best_result: 'Semi Finals (2022)',
    total_matches: 21,
    total_wins: 8,
    total_draws: 5,
    total_losses: 8,
    goals_scored: 25,
    goals_conceded: 18,
    top_scorer: { name: 'Youssef En-Nesyri', goals: 5 },
    most_capped: { name: 'Noureddine Naybet', caps: 8 },
    biggest_win: '3-0 vs Portugal (2022)',
    group_2026: 'C',
    history: [
      { year: 1970, result: 'Group Stage' },
      { year: 1986, result: 'Round of 16' },
      { year: 1994, result: 'Group Stage' },
      { year: 1998, result: 'Group Stage' },
      { year: 2018, result: 'Group Stage' },
      { year: 2022, result: 'Semi Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Haiti': {
    flag: 'ht',
    confederation: 'CONCACAF',
    fifa_ranking: 83,
    coach: 'Marc Collat',
    captain: 'Frantzdy Pierrot',
    all_time_appearances: 2,
    titles: 0,
    title_years: [],
    best_result: 'Group Stage',
    total_matches: 6,
    total_wins: 0,
    total_draws: 1,
    total_losses: 5,
    goals_scored: 4,
    goals_conceded: 15,
    top_scorer: { name: 'Emmanuel Sanon', goals: 2 },
    most_capped: { name: 'Pierre Bayol', caps: 3 },
    biggest_win: '2-1 vs Italy (1974)',
    group_2026: 'C',
    history: [
      { year: 1974, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Turkey': {
    flag: 'tr',
    confederation: 'UEFA',
    fifa_ranking: 26,
    coach: 'Vincenzo Montella',
    captain: 'Hakan Calhanoglu',
    all_time_appearances: 4,
    titles: 0,
    title_years: [],
    best_result: '3rd Place (2002)',
    total_matches: 10,
    total_wins: 5,
    total_draws: 1,
    total_losses: 4,
    goals_scored: 20,
    goals_conceded: 17,
    top_scorer: { name: 'Hakan Sukur', goals: 5 },
    most_capped: { name: 'Alpay Ozalan, Bulent Korkmaz, Tugay Kerimoglu', caps: 4 },
    biggest_win: '3-0 vs Senegal (2002)',
    group_2026: 'D',
    history: [
      { year: 1954, result: 'Group Stage' },
      { year: 1966, result: 'Group Stage' },
      { year: 2002, result: '3rd Place' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Paraguay': {
    flag: 'py',
    confederation: 'CONMEBOL',
    fifa_ranking: 51,
    coach: 'Gustavo Alfaro',
    captain: 'Miguel Almiron',
    all_time_appearances: 9,
    titles: 0,
    title_years: [],
    best_result: 'Quarter Finals (2010)',
    total_matches: 26,
    total_wins: 7,
    total_draws: 9,
    total_losses: 10,
    goals_scored: 27,
    goals_conceded: 36,
    top_scorer: { name: 'José Cardozo', goals: 4 },
    most_capped: { name: 'Carlos Gamarra', caps: 9 },
    biggest_win: '3-0 vs Belgium (1986)',
    group_2026: 'D',
    history: [
      { year: 1930, result: 'Group Stage' },
      { year: 1950, result: 'Group Stage' },
      { year: 1958, result: 'Group Stage' },
      { year: 1986, result: 'Round of 16' },
      { year: 1998, result: 'Round of 16' },
      { year: 2002, result: 'Round of 16' },
      { year: 2006, result: 'Group Stage' },
      { year: 2010, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Ecuador': {
    flag: 'ec',
    confederation: 'CONMEBOL',
    fifa_ranking: 44,
    coach: 'Sebastián Beccacece',
    captain: 'Enner Valencia',
    all_time_appearances: 4,
    titles: 0,
    title_years: [],
    best_result: 'Round of 16 (2006)',
    total_matches: 11,
    total_wins: 3,
    total_draws: 2,
    total_losses: 6,
    goals_scored: 11,
    goals_conceded: 20,
    top_scorer: { name: 'Enner Valencia', goals: 6 },
    most_capped: { name: 'Enner Valencia', caps: 4 },
    biggest_win: '3-0 vs Costa Rica (2006)',
    group_2026: 'E',
    history: [
      { year: 2002, result: 'Group Stage' },
      { year: 2006, result: 'Round of 16' },
      { year: 2014, result: 'Group Stage' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Ivory Coast': {
    flag: 'ci',
    confederation: 'CAF',
    fifa_ranking: 48,
    coach: 'Emerse Faé',
    captain: 'Sébastien Haller',
    all_time_appearances: 4,
    titles: 0,
    title_years: [],
    best_result: 'Group Stage',
    total_matches: 12,
    total_wins: 2,
    total_draws: 3,
    total_losses: 7,
    goals_scored: 12,
    goals_conceded: 21,
    top_scorer: { name: 'Didier Drogba', goals: 3 },
    most_capped: { name: 'Didier Drogba', caps: 4 },
    biggest_win: '2-1 vs Greece (2014)',
    group_2026: 'E',
    history: [
      { year: 2006, result: 'Group Stage' },
      { year: 2010, result: 'Group Stage' },
      { year: 2014, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Curacao': {
    flag: 'cw',
    confederation: 'CONCACAF',
    fifa_ranking: 84,
    coach: 'Sergio van Dijk',
    captain: 'Leandro Bacuna',
    all_time_appearances: 1,
    titles: 0,
    title_years: [],
    best_result: 'First World Cup! (2026)',
    total_matches: 0,
    total_wins: 0,
    total_draws: 0,
    total_losses: 0,
    goals_scored: 0,
    goals_conceded: 0,
    top_scorer: { name: 'TBD', goals: 0 },
    most_capped: { name: 'TBD', caps: 0 },
    biggest_win: 'TBD',
    group_2026: 'E',
    history: [
      { year: 2026, result: 'TBD' },
    ]
  },

  'Japan': {
    flag: 'jp',
    confederation: 'AFC',
    fifa_ranking: 15,
    coach: 'Hajime Moriyasu',
    captain: 'Wataru Endo',
    all_time_appearances: 8,
    titles: 0,
    title_years: [],
    best_result: 'Round of 16',
    total_matches: 24,
    total_wins: 9,
    total_draws: 4,
    total_losses: 11,
    goals_scored: 29,
    goals_conceded: 33,
    top_scorer: { name: 'Kunishige Kamamoto', goals: 4 },
    most_capped: { name: 'Yuto Nagatomo', caps: 8 },
    biggest_win: '4-0 vs Australia (2022)',
    group_2026: 'F',
    history: [
      { year: 1998, result: 'Group Stage' },
      { year: 2002, result: 'Round of 16' },
      { year: 2006, result: 'Group Stage' },
      { year: 2010, result: 'Round of 16' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: 'Round of 16' },
      { year: 2022, result: 'Round of 16' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Sweden': {
    flag: 'se',
    confederation: 'UEFA',
    fifa_ranking: 25,
    coach: 'Jon Dahl Tomasson',
    captain: 'Viktor Gyökeres',
    all_time_appearances: 13,
    titles: 0,
    title_years: [],
    best_result: 'Runners Up (1958)',
    total_matches: 46,
    total_wins: 18,
    total_draws: 11,
    total_losses: 17,
    goals_scored: 76,
    goals_conceded: 61,
    top_scorer: { name: 'Sven Rydell', goals: 8 },
    most_capped: { name: 'Thomas Ravelli', caps: 16 },
    biggest_win: '7-0 vs Cuba (1938)',
    group_2026: 'F',
    history: [
      { year: 1934, result: 'Quarter Finals' },
      { year: 1938, result: '4th Place' },
      { year: 1950, result: '3rd Place' },
      { year: 1958, result: 'Runners Up' },
      { year: 1970, result: 'Group Stage' },
      { year: 1974, result: 'Group Stage' },
      { year: 1978, result: 'Group Stage' },
      { year: 1990, result: 'Group Stage' },
      { year: 1994, result: '3rd Place' },
      { year: 2002, result: 'Round of 16' },
      { year: 2006, result: 'Round of 16' },
      { year: 2018, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Tunisia': {
    flag: 'tn',
    confederation: 'CAF',
    fifa_ranking: 30,
    coach: 'Jalel Kadri',
    captain: 'Youssef Msakni',
    all_time_appearances: 6,
    titles: 0,
    title_years: [],
    best_result: 'Group Stage',
    total_matches: 18,
    total_wins: 3,
    total_draws: 4,
    total_losses: 11,
    goals_scored: 14,
    goals_conceded: 30,
    top_scorer: { name: 'Wahbi Khazri', goals: 3 },
    most_capped: { name: 'Riadh Jelassi', caps: 6 },
    biggest_win: '3-1 vs Mexico (1978)',
    group_2026: 'F',
    history: [
      { year: 1978, result: 'Group Stage' },
      { year: 1998, result: 'Group Stage' },
      { year: 2002, result: 'Group Stage' },
      { year: 2006, result: 'Group Stage' },
      { year: 2018, result: 'Group Stage' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'New Zealand': {
    flag: 'nz',
    confederation: 'OFC',
    fifa_ranking: 92,
    coach: 'Darren Bazeley',
    captain: 'Tommy Smith',
    all_time_appearances: 3,
    titles: 0,
    title_years: [],
    best_result: 'Group Stage',
    total_matches: 9,
    total_wins: 0,
    total_draws: 3,
    total_losses: 6,
    goals_scored: 6,
    goals_conceded: 17,
    top_scorer: { name: 'Shane Smeltz', goals: 2 },
    most_capped: { name: 'Ivan Vicelich', caps: 4 },
    biggest_win: '1-1 vs Italy (2010)',
    group_2026: 'G',
    history: [
      { year: 1982, result: 'Group Stage' },
      { year: 2010, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Iran': {
    flag: 'ir',
    confederation: 'AFC',
    fifa_ranking: 22,
    coach: 'Amir Ghalenoei',
    captain: 'Alireza Jahanbakhsh',
    all_time_appearances: 7,
    titles: 0,
    title_years: [],
    best_result: 'Group Stage',
    total_matches: 21,
    total_wins: 3,
    total_draws: 4,
    total_losses: 14,
    goals_scored: 20,
    goals_conceded: 42,
    top_scorer: { name: 'Ali Daei', goals: 4 },
    most_capped: { name: 'Javad Nekounam', caps: 7 },
    biggest_win: '2-1 vs USA (1998)',
    group_2026: 'G',
    history: [
      { year: 1978, result: 'Group Stage' },
      { year: 1998, result: 'Group Stage' },
      { year: 2006, result: 'Group Stage' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: 'Group Stage' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Saudi Arabia': {
    flag: 'sa',
    confederation: 'AFC',
    fifa_ranking: 56,
    coach: 'Hervé Renard',
    captain: 'Salman Al-Faraj',
    all_time_appearances: 7,
    titles: 0,
    title_years: [],
    best_result: 'Round of 16 (1994)',
    total_matches: 19,
    total_wins: 4,
    total_draws: 2,
    total_losses: 13,
    goals_scored: 20,
    goals_conceded: 43,
    top_scorer: { name: 'Sami Al-Jaber', goals: 4 },
    most_capped: { name: 'Mohammed Al-Deayea', caps: 7 },
    biggest_win: '2-1 vs Argentina (2022)',
    group_2026: 'H',
    history: [
      { year: 1994, result: 'Round of 16' },
      { year: 1998, result: 'Group Stage' },
      { year: 2002, result: 'Group Stage' },
      { year: 2006, result: 'Group Stage' },
      { year: 2018, result: 'Group Stage' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Cape Verde': {
    flag: 'cv',
    confederation: 'CAF',
    fifa_ranking: 71,
    coach: 'Bubista',
    captain: 'Ryan Mendes',
    all_time_appearances: 1,
    titles: 0,
    title_years: [],
    best_result: 'First World Cup! (2026)',
    total_matches: 0,
    total_wins: 0,
    total_draws: 0,
    total_losses: 0,
    goals_scored: 0,
    goals_conceded: 0,
    top_scorer: { name: 'TBD', goals: 0 },
    most_capped: { name: 'TBD', caps: 0 },
    biggest_win: 'TBD',
    group_2026: 'H',
    history: [
      { year: 2026, result: 'TBD' },
    ]
  },

  'Norway': {
    flag: 'no',
    confederation: 'UEFA',
    fifa_ranking: 35,
    coach: 'Ståle Solbakken',
    captain: 'Martin Ødegaard',
    all_time_appearances: 4,
    titles: 0,
    title_years: [],
    best_result: 'Round of 16 (1998)',
    total_matches: 12,
    total_wins: 3,
    total_draws: 4,
    total_losses: 5,
    goals_scored: 13,
    goals_conceded: 17,
    top_scorer: { name: 'Jørgen Juve', goals: 4 },
    most_capped: { name: 'Henning Berg', caps: 4 },
    biggest_win: '3-2 vs Brazil (1998)',
    group_2026: 'I',
    history: [
      { year: 1938, result: 'Round of 16' },
      { year: 1994, result: 'Group Stage' },
      { year: 1998, result: 'Round of 16' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Senegal': {
    flag: 'sn',
    confederation: 'CAF',
    fifa_ranking: 17,
    coach: 'Aliou Cissé',
    captain: 'Sadio Mané',
    all_time_appearances: 4,
    titles: 0,
    title_years: [],
    best_result: 'Quarter Finals (2002)',
    total_matches: 13,
    total_wins: 5,
    total_draws: 3,
    total_losses: 5,
    goals_scored: 14,
    goals_conceded: 14,
    top_scorer: { name: 'Sadio Mané', goals: 3 },
    most_capped: { name: 'Aliou Cissé', caps: 4 },
    biggest_win: '3-0 vs Colombia (2018)',
    group_2026: 'I',
    history: [
      { year: 2002, result: 'Quarter Finals' },
      { year: 2018, result: 'Group Stage' },
      { year: 2022, result: 'Round of 16' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Iraq': {
    flag: 'iq',
    confederation: 'AFC',
    fifa_ranking: 58,
    coach: 'Jesús Casas',
    captain: 'Amjed Attwan',
    all_time_appearances: 2,
    titles: 0,
    title_years: [],
    best_result: 'Group Stage',
    total_matches: 6,
    total_wins: 0,
    total_draws: 1,
    total_losses: 5,
    goals_scored: 4,
    goals_conceded: 14,
    top_scorer: { name: 'Shaker Mahmood', goals: 2 },
    most_capped: { name: 'Hussein Saeed', caps: 3 },
    biggest_win: '1-1 vs Belgium (1986)',
    group_2026: 'I',
    history: [
      { year: 1986, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Jordan': {
    flag: 'jo',
    confederation: 'AFC',
    fifa_ranking: 66,
    coach: 'Hussein Ammouta',
    captain: 'Baha Faisal',
    all_time_appearances: 1,
    titles: 0,
    title_years: [],
    best_result: 'First World Cup! (2026)',
    total_matches: 0,
    total_wins: 0,
    total_draws: 0,
    total_losses: 0,
    goals_scored: 0,
    goals_conceded: 0,
    top_scorer: { name: 'TBD', goals: 0 },
    most_capped: { name: 'TBD', caps: 0 },
    biggest_win: 'TBD',
    group_2026: 'J',
    history: [
      { year: 2026, result: 'TBD' },
    ]
  },

  'Algeria': {
    flag: 'dz',
    confederation: 'CAF',
    fifa_ranking: 34,
    coach: 'Vladimir Petković',
    captain: 'Riyad Mahrez',
    all_time_appearances: 5,
    titles: 0,
    title_years: [],
    best_result: 'Round of 16 (2014)',
    total_matches: 15,
    total_wins: 4,
    total_draws: 3,
    total_losses: 8,
    goals_scored: 16,
    goals_conceded: 24,
    top_scorer: { name: 'Rabah Madjer', goals: 2 },
    most_capped: { name: 'Madjid Bougherra', caps: 5 },
    biggest_win: '3-0 vs Senegal (2002)',
    group_2026: 'J',
    history: [
      { year: 1982, result: 'Group Stage' },
      { year: 1986, result: 'Group Stage' },
      { year: 2010, result: 'Group Stage' },
      { year: 2014, result: 'Round of 16' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Uzbekistan': {
    flag: 'uz',
    confederation: 'AFC',
    fifa_ranking: 60,
    coach: 'Srecko Katanec',
    captain: 'Eldor Shomurodov',
    all_time_appearances: 1,
    titles: 0,
    title_years: [],
    best_result: 'First World Cup! (2026)',
    total_matches: 0,
    total_wins: 0,
    total_draws: 0,
    total_losses: 0,
    goals_scored: 0,
    goals_conceded: 0,
    top_scorer: { name: 'TBD', goals: 0 },
    most_capped: { name: 'TBD', caps: 0 },
    biggest_win: 'TBD',
    group_2026: 'K',
    history: [
      { year: 2026, result: 'TBD' },
    ]
  },

  'Ghana': {
    flag: 'gh',
    confederation: 'CAF',
    fifa_ranking: 55,
    coach: 'Otto Addo',
    captain: 'Andre Ayew',
    all_time_appearances: 4,
    titles: 0,
    title_years: [],
    best_result: 'Quarter Finals (2010)',
    total_matches: 13,
    total_wins: 4,
    total_draws: 3,
    total_losses: 6,
    goals_scored: 14,
    goals_conceded: 18,
    top_scorer: { name: 'Asamoah Gyan', goals: 6 },
    most_capped: { name: 'Asamoah Gyan', caps: 4 },
    biggest_win: '2-1 vs USA (2010)',
    group_2026: 'L',
    history: [
      { year: 2006, result: 'Round of 16' },
      { year: 2010, result: 'Quarter Finals' },
      { year: 2014, result: 'Group Stage' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Panama': {
    flag: 'pa',
    confederation: 'CONCACAF',
    fifa_ranking: 43,
    coach: 'Thomas Christiansen',
    captain: 'Román Torres',
    all_time_appearances: 2,
    titles: 0,
    title_years: [],
    best_result: 'Group Stage',
    total_matches: 6,
    total_wins: 0,
    total_draws: 0,
    total_losses: 6,
    goals_scored: 3,
    goals_conceded: 14,
    top_scorer: { name: 'Blas Pérez', goals: 1 },
    most_capped: { name: 'Roman Torres', caps: 3 },
    biggest_win: '1-0 vs Tunisia (2018)',
    group_2026: 'L',
    history: [
      { year: 2018, result: 'Group Stage' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },
  

}

export default COUNTRY_DATA