// ============================================================
// COUNTRY DATA — World Cup history, stats and records
// Sources: Wikipedia, FIFA.com
// ============================================================

const COUNTRY_DATA = {

  'Brazil': {
    flag: 'br',
    confederation: 'CONMEBOL',
    fifa_ranking: 5,
    coach: 'Carlo Ancelotti',
    captain: 'Marquinhos',
    all_time_appearances: 22,
    titles: 5,
    title_years: [1958, 1962, 1970, 1994, 2002],
    best_result: '🏆 5x World Cup Champions',
    total_matches: 114,
    total_wins: 76,
    total_draws: 18,
    total_losses: 20,
    goals_scored: 237,
    goals_conceded: 101,
    top_scorer: { name: 'Ronaldo', goals: 15 },
    most_capped: { name: 'Cafu', caps: 142 },
    biggest_win: '7-1 vs Germany (2014 SF) — but as hosts losing',
    group_2026: 'C',
    history: [
      { year: 1930, result: 'Semi Finals' },
      { year: 1934, result: 'Round of 16' },
      { year: 1938, result: 'Semi Finals' },
      { year: 1950, result: 'Runners Up' },
      { year: 1954, result: 'Quarter Finals' },
      { year: 1958, result: '🏆 Champions' },
      { year: 1962, result: '🏆 Champions' },
      { year: 1966, result: 'Group Stage' },
      { year: 1970, result: '🏆 Champions' },
      { year: 1974, result: '4th Place' },
      { year: 1978, result: '3rd Place' },
      { year: 1982, result: 'Round of 16' },
      { year: 1986, result: 'Quarter Finals' },
      { year: 1990, result: 'Round of 16' },
      { year: 1994, result: '🏆 Champions' },
      { year: 1998, result: 'Runners Up' },
      { year: 2002, result: '🏆 Champions' },
      { year: 2006, result: 'Quarter Finals' },
      { year: 2010, result: 'Quarter Finals' },
      { year: 2014, result: '4th Place' },
      { year: 2018, result: 'Quarter Finals' },
      { year: 2022, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'France': {
    flag: 'fr',
    confederation: 'UEFA',
    fifa_ranking: 2,
    coach: 'Didier Deschamps',
    captain: 'Kylian Mbappé',
    all_time_appearances: 16,
    titles: 2,
    title_years: [1998, 2018],
    best_result: '🏆 2x World Cup Champions',
    total_matches: 66,
    total_wins: 38,
    total_draws: 13,
    total_losses: 15,
    goals_scored: 120,
    goals_conceded: 68,
    top_scorer: { name: 'Just Fontaine', goals: 13 },
    most_capped: { name: 'Hugo Lloris', caps: 145 },
    biggest_win: '10-0 vs Azerbaijan (2021 WCQ)',
    group_2026: 'I',
    history: [
      { year: 1930, result: 'Group Stage' },
      { year: 1934, result: 'Round of 16' },
      { year: 1938, result: 'Quarter Finals' },
      { year: 1954, result: 'Group Stage' },
      { year: 1958, result: '3rd Place' },
      { year: 1966, result: 'Group Stage' },
      { year: 1978, result: 'Group Stage' },
      { year: 1982, result: '4th Place' },
      { year: 1986, result: '3rd Place' },
      { year: 1998, result: '🏆 Champions' },
      { year: 2002, result: 'Group Stage' },
      { year: 2006, result: 'Runners Up' },
      { year: 2010, result: 'Group Stage' },
      { year: 2014, result: 'Quarter Finals' },
      { year: 2018, result: '🏆 Champions' },
      { year: 2022, result: 'Runners Up' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Argentina': {
    flag: 'ar',
    confederation: 'CONMEBOL',
    fifa_ranking: 1,
    coach: 'Lionel Scaloni',
    captain: 'Lionel Messi',
    all_time_appearances: 19,
    titles: 3,
    title_years: [1978, 1986, 2022],
    best_result: '🏆 3x World Cup Champions',
    total_matches: 88,
    total_wins: 47,
    total_draws: 15,
    total_losses: 26,
    goals_scored: 145,
    goals_conceded: 97,
    top_scorer: { name: 'Gabriel Batistuta', goals: 10 },
    most_capped: { name: 'Lionel Messi', caps: 191 },
    biggest_win: '6-0 vs Serbia & Montenegro (2006)',
    group_2026: 'J',
    history: [
      { year: 1930, result: 'Runners Up' },
      { year: 1934, result: 'Round of 16' },
      { year: 1958, result: 'Group Stage' },
      { year: 1962, result: 'Group Stage' },
      { year: 1966, result: 'Quarter Finals' },
      { year: 1974, result: 'Round of 16' },
      { year: 1978, result: '🏆 Champions' },
      { year: 1982, result: 'Round of 16' },
      { year: 1986, result: '🏆 Champions' },
      { year: 1990, result: 'Runners Up' },
      { year: 1994, result: 'Round of 16' },
      { year: 1998, result: 'Quarter Finals' },
      { year: 2002, result: 'Group Stage' },
      { year: 2006, result: 'Quarter Finals' },
      { year: 2010, result: 'Quarter Finals' },
      { year: 2014, result: 'Runners Up' },
      { year: 2018, result: 'Round of 16' },
      { year: 2022, result: '🏆 Champions' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'England': {
    flag: 'gb-eng',
    confederation: 'UEFA',
    fifa_ranking: 4,
    coach: 'Thomas Tuchel',
    captain: 'Harry Kane',
    all_time_appearances: 16,
    titles: 1,
    title_years: [1966],
    best_result: '🏆 1966 World Cup Champions',
    total_matches: 69,
    total_wins: 33,
    total_draws: 21,
    total_losses: 15,
    goals_scored: 100,
    goals_conceded: 60,
    top_scorer: { name: 'Harry Kane', goals: 68 },
    most_capped: { name: 'Peter Shilton', caps: 125 },
    biggest_win: '8-0 vs Mexico (1961 friendly)',
    group_2026: 'L',
    history: [
      { year: 1950, result: 'Group Stage' },
      { year: 1954, result: 'Quarter Finals' },
      { year: 1958, result: 'Group Stage' },
      { year: 1962, result: 'Quarter Finals' },
      { year: 1966, result: '🏆 Champions' },
      { year: 1970, result: 'Quarter Finals' },
      { year: 1982, result: 'Round of 16' },
      { year: 1986, result: 'Quarter Finals' },
      { year: 1990, result: '4th Place' },
      { year: 1998, result: 'Round of 16' },
      { year: 2002, result: 'Quarter Finals' },
      { year: 2006, result: 'Quarter Finals' },
      { year: 2010, result: 'Round of 16' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: '4th Place' },
      { year: 2022, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Spain': {
    flag: 'es',
    confederation: 'UEFA',
    fifa_ranking: 3,
    coach: 'Luis de la Fuente',
    captain: 'Álvaro Morata',
    all_time_appearances: 16,
    titles: 1,
    title_years: [2010],
    best_result: '🏆 2010 World Cup Champions',
    total_matches: 67,
    total_wins: 34,
    total_draws: 16,
    total_losses: 17,
    goals_scored: 110,
    goals_conceded: 72,
    top_scorer: { name: 'David Villa', goals: 59 },
    most_capped: { name: 'Sergio Ramos', caps: 180 },
    biggest_win: '7-0 vs Costa Rica (2022)',
    group_2026: 'H',
    history: [
      { year: 1934, result: 'Quarter Finals' },
      { year: 1950, result: '4th Place' },
      { year: 1962, result: 'Group Stage' },
      { year: 1966, result: 'Group Stage' },
      { year: 1978, result: 'Round of 16' },
      { year: 1982, result: 'Round of 16' },
      { year: 1986, result: 'Quarter Finals' },
      { year: 1990, result: 'Round of 16' },
      { year: 1994, result: 'Quarter Finals' },
      { year: 1998, result: 'Round of 16' },
      { year: 2002, result: 'Quarter Finals' },
      { year: 2006, result: 'Round of 16' },
      { year: 2010, result: '🏆 Champions' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: 'Round of 16' },
      { year: 2022, result: 'Round of 16' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Germany': {
    flag: 'de',
    confederation: 'UEFA',
    fifa_ranking: 12,
    coach: 'Julian Nagelsmann',
    captain: 'Joshua Kimmich',
    all_time_appearances: 20,
    titles: 4,
    title_years: [1954, 1974, 1990, 2014],
    best_result: '🏆 4x World Cup Champions',
    total_matches: 109,
    total_wins: 67,
    total_draws: 20,
    total_losses: 22,
    goals_scored: 226,
    goals_conceded: 125,
    top_scorer: { name: 'Miroslav Klose', goals: 16 },
    most_capped: { name: 'Lothar Matthäus', caps: 150 },
    biggest_win: '8-0 vs Saudi Arabia (2002)',
    group_2026: 'E',
    history: [
      { year: 1934, result: '3rd Place' },
      { year: 1938, result: 'Round of 16' },
      { year: 1954, result: '🏆 Champions' },
      { year: 1958, result: '4th Place' },
      { year: 1962, result: 'Quarter Finals' },
      { year: 1966, result: 'Runners Up' },
      { year: 1970, result: '3rd Place' },
      { year: 1974, result: '🏆 Champions' },
      { year: 1978, result: 'Round of 16' },
      { year: 1982, result: 'Runners Up' },
      { year: 1986, result: 'Runners Up' },
      { year: 1990, result: '🏆 Champions' },
      { year: 1994, result: 'Quarter Finals' },
      { year: 1998, result: 'Quarter Finals' },
      { year: 2002, result: 'Runners Up' },
      { year: 2006, result: '3rd Place' },
      { year: 2010, result: '3rd Place' },
      { year: 2014, result: '🏆 Champions' },
      { year: 2018, result: 'Group Stage' },
      { year: 2022, result: 'Group Stage' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Portugal': {
    flag: 'pt',
    confederation: 'UEFA',
    fifa_ranking: 6,
    coach: 'Roberto Martínez',
    captain: 'Cristiano Ronaldo',
    all_time_appearances: 9,
    titles: 0,
    title_years: [],
    best_result: '3rd Place (1966)',
    total_matches: 37,
    total_wins: 18,
    total_draws: 8,
    total_losses: 11,
    goals_scored: 63,
    goals_conceded: 43,
    top_scorer: { name: 'Cristiano Ronaldo', goals: 143 },
    most_capped: { name: 'Cristiano Ronaldo', caps: 226 },
    biggest_win: '7-0 vs North Korea (2010)',
    group_2026: 'K',
    history: [
      { year: 1966, result: '3rd Place' },
      { year: 1986, result: 'Round of 16' },
      { year: 2002, result: 'Group Stage' },
      { year: 2006, result: '4th Place' },
      { year: 2010, result: 'Round of 16' },
      { year: 2014, result: 'Group Stage' },
      { year: 2018, result: 'Round of 16' },
      { year: 2022, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },

  'Netherlands': {
    flag: 'nl',
    confederation: 'UEFA',
    fifa_ranking: 7,
    coach: 'Ronald Koeman',
    captain: 'Virgil van Dijk',
    all_time_appearances: 11,
    titles: 0,
    title_years: [],
    best_result: 'Runners Up (1974, 1978, 2010)',
    total_matches: 52,
    total_wins: 29,
    total_draws: 10,
    total_losses: 13,
    goals_scored: 99,
    goals_conceded: 57,
    top_scorer: { name: 'Robin van Persie', goals: 50 },
    most_capped: { name: 'Wesley Sneijder', caps: 134 },
    biggest_win: '7-0 vs Spain (2014)',
    group_2026: 'F',
    history: [
      { year: 1934, result: 'Round of 16' },
      { year: 1938, result: 'Round of 16' },
      { year: 1974, result: 'Runners Up' },
      { year: 1978, result: 'Runners Up' },
      { year: 1990, result: 'Round of 16' },
      { year: 1994, result: 'Quarter Finals' },
      { year: 1998, result: '4th Place' },
      { year: 2006, result: 'Round of 16' },
      { year: 2010, result: 'Runners Up' },
      { year: 2014, result: '3rd Place' },
      { year: 2022, result: 'Quarter Finals' },
      { year: 2026, result: 'TBD' },
    ]
  },
}

export default COUNTRY_DATA