// ============================================================
// WORLD CUP 2026 — OFFICIAL PLAYER DATABASE
// Sourced from confirmed squads as of May 29, 2026
// Will be updated June 2 when FIFA officially confirms all squads
// ============================================================

const PLAYERS = [

  // ======================== ARGENTINA ========================
  { name: 'Lionel Messi', country: 'Argentina', flag: 'ar', position: 'Forward' },
  { name: 'Lautaro Martínez', country: 'Argentina', flag: 'ar', position: 'Forward' },
  { name: 'Julián Álvarez', country: 'Argentina', flag: 'ar', position: 'Forward' },
  { name: 'Paulo Dybala', country: 'Argentina', flag: 'ar', position: 'Forward' },
  { name: 'Enzo Fernández', country: 'Argentina', flag: 'ar', position: 'Midfielder' },
  { name: 'Rodrigo De Paul', country: 'Argentina', flag: 'ar', position: 'Midfielder' },
  { name: 'Alexis Mac Allister', country: 'Argentina', flag: 'ar', position: 'Midfielder' },
  { name: 'Giovani Lo Celso', country: 'Argentina', flag: 'ar', position: 'Midfielder' },
  { name: 'Claudio Echeverri', country: 'Argentina', flag: 'ar', position: 'Midfielder' },
  { name: 'Franco Mastantuono', country: 'Argentina', flag: 'ar', position: 'Midfielder' },
  { name: 'Emiliano Martínez', country: 'Argentina', flag: 'ar', position: 'Goalkeeper' },
  { name: 'Cristian Romero', country: 'Argentina', flag: 'ar', position: 'Defender' },
  { name: 'Nicolás Otamendi', country: 'Argentina', flag: 'ar', position: 'Defender' },
  { name: 'Nahuel Molina', country: 'Argentina', flag: 'ar', position: 'Defender' },
  { name: 'Nicolás Tagliafico', country: 'Argentina', flag: 'ar', position: 'Defender' },

  // ======================== FRANCE ========================
  { name: 'Kylian Mbappé', country: 'France', flag: 'fr', position: 'Forward' },
  { name: 'Marcus Thuram', country: 'France', flag: 'fr', position: 'Forward' },
  { name: 'Ousmane Dembélé', country: 'France', flag: 'fr', position: 'Forward' },
  { name: 'Bradley Barcola', country: 'France', flag: 'fr', position: 'Forward' },
  { name: 'Rayan Cherki', country: 'France', flag: 'fr', position: 'Forward' },
  { name: 'Michael Olise', country: 'France', flag: 'fr', position: 'Forward' },
  { name: 'Maghnes Akliouche', country: 'France', flag: 'fr', position: 'Forward' },
  { name: 'Jean-Philippe Mateta', country: 'France', flag: 'fr', position: 'Forward' },
  { name: 'Désiré Doué', country: 'France', flag: 'fr', position: 'Forward' },
  { name: 'Aurélien Tchouaméni', country: 'France', flag: 'fr', position: 'Midfielder' },
  { name: 'Adrien Rabiot', country: 'France', flag: 'fr', position: 'Midfielder' },
  { name: "N'Golo Kanté", country: 'France', flag: 'fr', position: 'Midfielder' },
  { name: 'Manu Koné', country: 'France', flag: 'fr', position: 'Midfielder' },
  { name: 'Warren Zaïre-Emery', country: 'France', flag: 'fr', position: 'Midfielder' },
  { name: 'Mike Maignan', country: 'France', flag: 'fr', position: 'Goalkeeper' },
  { name: 'Brice Samba', country: 'France', flag: 'fr', position: 'Goalkeeper' },
  { name: 'Robin Risser', country: 'France', flag: 'fr', position: 'Goalkeeper' },
  { name: 'William Saliba', country: 'France', flag: 'fr', position: 'Defender' },
  { name: 'Jules Koundé', country: 'France', flag: 'fr', position: 'Defender' },
  { name: 'Ibrahima Konaté', country: 'France', flag: 'fr', position: 'Defender' },
  { name: 'Théo Hernández', country: 'France', flag: 'fr', position: 'Defender' },
  { name: 'Lucas Hernández', country: 'France', flag: 'fr', position: 'Defender' },
  { name: 'Dayot Upamecano', country: 'France', flag: 'fr', position: 'Defender' },
  { name: 'Malo Gusto', country: 'France', flag: 'fr', position: 'Defender' },
  { name: 'Lucas Digne', country: 'France', flag: 'fr', position: 'Defender' },
  { name: 'Maxence Lacroix', country: 'France', flag: 'fr', position: 'Defender' },

  // ======================== BRAZIL ========================
  { name: 'Vinícius Jr.', country: 'Brazil', flag: 'br', position: 'Forward' },
  { name: 'Raphinha', country: 'Brazil', flag: 'br', position: 'Forward' },
  { name: 'Neymar', country: 'Brazil', flag: 'br', position: 'Forward' },
  { name: 'Endrick', country: 'Brazil', flag: 'br', position: 'Forward' },
  { name: 'Gabriel Martinelli', country: 'Brazil', flag: 'br', position: 'Forward' },
  { name: 'Matheus Cunha', country: 'Brazil', flag: 'br', position: 'Forward' },
  { name: 'Igor Thiago', country: 'Brazil', flag: 'br', position: 'Forward' },
  { name: 'Savinho', country: 'Brazil', flag: 'br', position: 'Forward' },
  { name: 'Luiz Henrique', country: 'Brazil', flag: 'br', position: 'Forward' },
  { name: 'Casemiro', country: 'Brazil', flag: 'br', position: 'Midfielder' },
  { name: 'Lucas Paquetá', country: 'Brazil', flag: 'br', position: 'Midfielder' },
  { name: 'Bruno Guimarães', country: 'Brazil', flag: 'br', position: 'Midfielder' },
  { name: 'Fabinho', country: 'Brazil', flag: 'br', position: 'Midfielder' },
  { name: 'Danilo Santos', country: 'Brazil', flag: 'br', position: 'Midfielder' },
  { name: 'Alisson', country: 'Brazil', flag: 'br', position: 'Goalkeeper' },
  { name: 'Marquinhos', country: 'Brazil', flag: 'br', position: 'Defender' },
  { name: 'Gabriel Magalhães', country: 'Brazil', flag: 'br', position: 'Defender' },
  { name: 'Militão', country: 'Brazil', flag: 'br', position: 'Defender' },
  { name: 'Bremer', country: 'Brazil', flag: 'br', position: 'Defender' },
  { name: 'Alex Sandro', country: 'Brazil', flag: 'br', position: 'Defender' },
  { name: 'Danilo Luiz', country: 'Brazil', flag: 'br', position: 'Defender' },
  { name: 'Wesley', country: 'Brazil', flag: 'br', position: 'Defender' },

  // ======================== ENGLAND ========================
  { name: 'Harry Kane', country: 'England', flag: 'gb-eng', position: 'Forward' },
  { name: 'Jude Bellingham', country: 'England', flag: 'gb-eng', position: 'Midfielder' },
  { name: 'Bukayo Saka', country: 'England', flag: 'gb-eng', position: 'Forward' },
  { name: 'Declan Rice', country: 'England', flag: 'gb-eng', position: 'Midfielder' },
  { name: 'Marcus Rashford', country: 'England', flag: 'gb-eng', position: 'Forward' },
  { name: 'Ollie Watkins', country: 'England', flag: 'gb-eng', position: 'Forward' },
  { name: 'Eberechi Eze', country: 'England', flag: 'gb-eng', position: 'Midfielder' },
  { name: 'Conor Gallagher', country: 'England', flag: 'gb-eng', position: 'Midfielder' },
  { name: 'Jordan Pickford', country: 'England', flag: 'gb-eng', position: 'Goalkeeper' },
  { name: 'Nick Pope', country: 'England', flag: 'gb-eng', position: 'Goalkeeper' },
  { name: 'Kyle Walker', country: 'England', flag: 'gb-eng', position: 'Defender' },
  { name: 'John Stones', country: 'England', flag: 'gb-eng', position: 'Defender' },
  { name: 'Marc Guéhi', country: 'England', flag: 'gb-eng', position: 'Defender' },
  { name: 'Luke Shaw', country: 'England', flag: 'gb-eng', position: 'Defender' },
  { name: 'Levi Colwill', country: 'England', flag: 'gb-eng', position: 'Defender' },
  { name: 'George Hirst', country: 'England', flag: 'gb-eng', position: 'Forward' },

  // ======================== PORTUGAL ========================
  { name: 'Cristiano Ronaldo', country: 'Portugal', flag: 'pt', position: 'Forward' },
  { name: 'Bruno Fernandes', country: 'Portugal', flag: 'pt', position: 'Midfielder' },
  { name: 'Bernardo Silva', country: 'Portugal', flag: 'pt', position: 'Midfielder' },
  { name: 'Rafael Leão', country: 'Portugal', flag: 'pt', position: 'Forward' },
  { name: 'Pedro Neto', country: 'Portugal', flag: 'pt', position: 'Forward' },
  { name: 'Gonçalo Ramos', country: 'Portugal', flag: 'pt', position: 'Forward' },
  { name: 'Diogo Jota', country: 'Portugal', flag: 'pt', position: 'Forward' },
  { name: 'João Neves', country: 'Portugal', flag: 'pt', position: 'Midfielder' },
  { name: 'Vitinha', country: 'Portugal', flag: 'pt', position: 'Midfielder' },
  { name: 'Diogo Costa', country: 'Portugal', flag: 'pt', position: 'Goalkeeper' },
  { name: 'Rúben Dias', country: 'Portugal', flag: 'pt', position: 'Defender' },
  { name: 'João Cancelo', country: 'Portugal', flag: 'pt', position: 'Defender' },
  { name: 'Nuno Mendes', country: 'Portugal', flag: 'pt', position: 'Defender' },

  // ======================== SPAIN ========================
  { name: 'Lamine Yamal', country: 'Spain', flag: 'es', position: 'Forward' },
  { name: 'Nico Williams', country: 'Spain', flag: 'es', position: 'Forward' },
  { name: 'Álvaro Morata', country: 'Spain', flag: 'es', position: 'Forward' },
  { name: 'Ferran Torres', country: 'Spain', flag: 'es', position: 'Forward' },
  { name: 'Mikel Oyarzabal', country: 'Spain', flag: 'es', position: 'Forward' },
  { name: 'Yéremy Pino', country: 'Spain', flag: 'es', position: 'Forward' },
  { name: 'Pedri', country: 'Spain', flag: 'es', position: 'Midfielder' },
  { name: 'Gavi', country: 'Spain', flag: 'es', position: 'Midfielder' },
  { name: 'Rodri', country: 'Spain', flag: 'es', position: 'Midfielder' },
  { name: 'Dani Olmo', country: 'Spain', flag: 'es', position: 'Midfielder' },
  { name: 'Fabián Ruiz', country: 'Spain', flag: 'es', position: 'Midfielder' },
  { name: 'Martín Zubimendi', country: 'Spain', flag: 'es', position: 'Midfielder' },
  { name: 'Álex Baena', country: 'Spain', flag: 'es', position: 'Midfielder' },
  { name: 'Unai Simón', country: 'Spain', flag: 'es', position: 'Goalkeeper' },
  { name: 'Aymeric Laporte', country: 'Spain', flag: 'es', position: 'Defender' },
  { name: 'Robin Le Normand', country: 'Spain', flag: 'es', position: 'Defender' },
  { name: 'Dani Carvajal', country: 'Spain', flag: 'es', position: 'Defender' },

  // ======================== GERMANY ========================
  { name: 'Florian Wirtz', country: 'Germany', flag: 'de', position: 'Midfielder' },
  { name: 'Jamal Musiala', country: 'Germany', flag: 'de', position: 'Midfielder' },
  { name: 'Joshua Kimmich', country: 'Germany', flag: 'de', position: 'Midfielder' },
  { name: 'Toni Kroos', country: 'Germany', flag: 'de', position: 'Midfielder' },
  { name: 'Kai Havertz', country: 'Germany', flag: 'de', position: 'Forward' },
  { name: 'Leroy Sané', country: 'Germany', flag: 'de', position: 'Forward' },
  { name: 'Niclas Füllkrug', country: 'Germany', flag: 'de', position: 'Forward' },
  { name: 'Thomas Müller', country: 'Germany', flag: 'de', position: 'Forward' },
  { name: 'Serge Gnabry', country: 'Germany', flag: 'de', position: 'Forward' },
  { name: 'Manuel Neuer', country: 'Germany', flag: 'de', position: 'Goalkeeper' },
  { name: 'Antonio Rüdiger', country: 'Germany', flag: 'de', position: 'Defender' },
  { name: 'Nico Schlotterbeck', country: 'Germany', flag: 'de', position: 'Defender' },
  { name: 'Benjamin Pavard', country: 'Germany', flag: 'de', position: 'Defender' },

  // ======================== NETHERLANDS ========================
  { name: 'Virgil van Dijk', country: 'Netherlands', flag: 'nl', position: 'Defender' },
  { name: 'Cody Gakpo', country: 'Netherlands', flag: 'nl', position: 'Forward' },
  { name: 'Memphis Depay', country: 'Netherlands', flag: 'nl', position: 'Forward' },
  { name: 'Brian Brobbey', country: 'Netherlands', flag: 'nl', position: 'Forward' },
  { name: 'Donyell Malen', country: 'Netherlands', flag: 'nl', position: 'Forward' },
  { name: 'Xavi Simons', country: 'Netherlands', flag: 'nl', position: 'Midfielder' },
  { name: 'Frenkie de Jong', country: 'Netherlands', flag: 'nl', position: 'Midfielder' },
  { name: 'Ryan Gravenberch', country: 'Netherlands', flag: 'nl', position: 'Midfielder' },
  { name: 'Tijjani Reijnders', country: 'Netherlands', flag: 'nl', position: 'Midfielder' },
  { name: 'Bart Verbruggen', country: 'Netherlands', flag: 'nl', position: 'Goalkeeper' },
  { name: 'Denzel Dumfries', country: 'Netherlands', flag: 'nl', position: 'Defender' },
  { name: 'Nathan Aké', country: 'Netherlands', flag: 'nl', position: 'Defender' },

  // ======================== USA ========================
  { name: 'Christian Pulisic', country: 'USA', flag: 'us', position: 'Forward' },
  { name: 'Tyler Adams', country: 'USA', flag: 'us', position: 'Midfielder' },
  { name: 'Weston McKennie', country: 'USA', flag: 'us', position: 'Midfielder' },
  { name: 'Yunus Musah', country: 'USA', flag: 'us', position: 'Midfielder' },
  { name: 'Gio Reyna', country: 'USA', flag: 'us', position: 'Midfielder' },
  { name: 'Ricardo Pepi', country: 'USA', flag: 'us', position: 'Forward' },
  { name: 'Josh Sargent', country: 'USA', flag: 'us', position: 'Forward' },
  { name: 'Folarin Balogun', country: 'USA', flag: 'us', position: 'Forward' },
  { name: 'Matt Turner', country: 'USA', flag: 'us', position: 'Goalkeeper' },
  { name: 'Walker Zimmerman', country: 'USA', flag: 'us', position: 'Defender' },
  { name: 'Sergiño Dest', country: 'USA', flag: 'us', position: 'Defender' },
  { name: 'Tim Weah', country: 'USA', flag: 'us', position: 'Forward' },
  { name: 'Antonee Robinson', country: 'USA', flag: 'us', position: 'Defender' },

  // ======================== CANADA ========================
  { name: 'Alphonso Davies', country: 'Canada', flag: 'ca', position: 'Defender' },
  { name: 'Jonathan David', country: 'Canada', flag: 'ca', position: 'Forward' },
  { name: 'Cyle Larin', country: 'Canada', flag: 'ca', position: 'Forward' },
  { name: 'Tajon Buchanan', country: 'Canada', flag: 'ca', position: 'Forward' },
  { name: 'Stephen Eustáquio', country: 'Canada', flag: 'ca', position: 'Midfielder' },
  { name: 'Atiba Hutchinson', country: 'Canada', flag: 'ca', position: 'Midfielder' },
  { name: 'Milan Borjan', country: 'Canada', flag: 'ca', position: 'Goalkeeper' },
  { name: 'Kamal Miller', country: 'Canada', flag: 'ca', position: 'Defender' },
  { name: 'Derek Cornelius', country: 'Canada', flag: 'ca', position: 'Defender' },

  // ======================== MEXICO ========================
  { name: 'Raúl Jiménez', country: 'Mexico', flag: 'mx', position: 'Forward' },
  { name: 'Santiago Giménez', country: 'Mexico', flag: 'mx', position: 'Forward' },
  { name: 'Hirving Lozano', country: 'Mexico', flag: 'mx', position: 'Forward' },
  { name: 'Edson Álvarez', country: 'Mexico', flag: 'mx', position: 'Midfielder' },
  { name: 'Guillermo Ochoa', country: 'Mexico', flag: 'mx', position: 'Goalkeeper' },
  { name: 'César Montes', country: 'Mexico', flag: 'mx', position: 'Defender' },
  { name: 'Julián Quiñones', country: 'Mexico', flag: 'mx', position: 'Forward' },
  { name: 'César Huerta', country: 'Mexico', flag: 'mx', position: 'Forward' },
  { name: 'Álvaro Fidalgo', country: 'Mexico', flag: 'mx', position: 'Midfielder' },
  { name: 'Obed Vargas', country: 'Mexico', flag: 'mx', position: 'Midfielder' },

  // ======================== CROATIA ========================
  { name: 'Luka Modrić', country: 'Croatia', flag: 'hr', position: 'Midfielder' },
  { name: 'Ivan Perišić', country: 'Croatia', flag: 'hr', position: 'Forward' },
  { name: 'Mateo Kovačić', country: 'Croatia', flag: 'hr', position: 'Midfielder' },
  { name: 'Marcelo Brozović', country: 'Croatia', flag: 'hr', position: 'Midfielder' },
  { name: 'Joško Gvardiol', country: 'Croatia', flag: 'hr', position: 'Defender' },
  { name: 'Andrej Kramarić', country: 'Croatia', flag: 'hr', position: 'Forward' },
  { name: 'Bruno Petković', country: 'Croatia', flag: 'hr', position: 'Forward' },
  { name: 'Ante Budimir', country: 'Croatia', flag: 'hr', position: 'Forward' },
  { name: 'Dominik Livaković', country: 'Croatia', flag: 'hr', position: 'Goalkeeper' },
  { name: 'Mario Pašalić', country: 'Croatia', flag: 'hr', position: 'Midfielder' },

  // ======================== MOROCCO ========================
  { name: 'Achraf Hakimi', country: 'Morocco', flag: 'ma', position: 'Defender' },
  { name: 'Hakim Ziyech', country: 'Morocco', flag: 'ma', position: 'Midfielder' },
  { name: 'Yassine Bounou', country: 'Morocco', flag: 'ma', position: 'Goalkeeper' },
  { name: 'Sofyan Amrabat', country: 'Morocco', flag: 'ma', position: 'Midfielder' },
  { name: 'Azzedine Ounahi', country: 'Morocco', flag: 'ma', position: 'Midfielder' },
  { name: 'Youssef En-Nesyri', country: 'Morocco', flag: 'ma', position: 'Forward' },
  { name: 'Noussair Mazraoui', country: 'Morocco', flag: 'ma', position: 'Defender' },
  { name: 'Abde Ezzalzouli', country: 'Morocco', flag: 'ma', position: 'Forward' },
  { name: 'Romain Saïss', country: 'Morocco', flag: 'ma', position: 'Defender' },

  // ======================== SENEGAL ========================
  { name: 'Sadio Mané', country: 'Senegal', flag: 'sn', position: 'Forward' },
  { name: 'Ismaila Sarr', country: 'Senegal', flag: 'sn', position: 'Forward' },
  { name: 'Nicolas Jackson', country: 'Senegal', flag: 'sn', position: 'Forward' },
  { name: 'Iliman Ndiaye', country: 'Senegal', flag: 'sn', position: 'Forward' },
  { name: 'Assane Diao', country: 'Senegal', flag: 'sn', position: 'Forward' },
  { name: 'Bamba Dieng', country: 'Senegal', flag: 'sn', position: 'Forward' },
  { name: 'Idrissa Gueye', country: 'Senegal', flag: 'sn', position: 'Midfielder' },
  { name: 'Pape Matar Sarr', country: 'Senegal', flag: 'sn', position: 'Midfielder' },
  { name: 'Lamine Camara', country: 'Senegal', flag: 'sn', position: 'Midfielder' },
  { name: 'Habib Diarra', country: 'Senegal', flag: 'sn', position: 'Midfielder' },
  { name: 'Édouard Mendy', country: 'Senegal', flag: 'sn', position: 'Goalkeeper' },
  { name: 'Kalidou Koulibaly', country: 'Senegal', flag: 'sn', position: 'Defender' },
  { name: 'Krepin Diatta', country: 'Senegal', flag: 'sn', position: 'Defender' },
  { name: 'Moussa Niakhaté', country: 'Senegal', flag: 'sn', position: 'Defender' },

  // ======================== EGYPT ========================
  { name: 'Mohamed Salah', country: 'Egypt', flag: 'eg', position: 'Forward' },
  { name: 'Mostafa Mohamed', country: 'Egypt', flag: 'eg', position: 'Forward' },
  { name: 'Omar Marmoush', country: 'Egypt', flag: 'eg', position: 'Forward' },
  { name: 'Mahmoud Trezeguet', country: 'Egypt', flag: 'eg', position: 'Forward' },
  { name: 'Mohamed Elneny', country: 'Egypt', flag: 'eg', position: 'Midfielder' },
  { name: 'Tarek Hamed', country: 'Egypt', flag: 'eg', position: 'Midfielder' },
  { name: 'Mohamed El-Shenawy', country: 'Egypt', flag: 'eg', position: 'Goalkeeper' },
  { name: 'Ahmed Hegazi', country: 'Egypt', flag: 'eg', position: 'Defender' },

  // ======================== NORWAY ========================
  { name: 'Erling Haaland', country: 'Norway', flag: 'no', position: 'Forward' },
  { name: 'Martin Ødegaard', country: 'Norway', flag: 'no', position: 'Midfielder' },
  { name: 'Alexander Sørloth', country: 'Norway', flag: 'no', position: 'Forward' },
  { name: 'Sander Berge', country: 'Norway', flag: 'no', position: 'Midfielder' },
  { name: 'Mohamed Elyounoussi', country: 'Norway', flag: 'no', position: 'Forward' },
  { name: 'Ørjan Nyland', country: 'Norway', flag: 'no', position: 'Goalkeeper' },
  { name: 'Leo Østigård', country: 'Norway', flag: 'no', position: 'Defender' },
  { name: 'Morten Thorsby', country: 'Norway', flag: 'no', position: 'Midfielder' },
  { name: 'Antonio Nusa', country: 'Norway', flag: 'no', position: 'Forward' },

  // ======================== ALGERIA ========================
  { name: 'Riyad Mahrez', country: 'Algeria', flag: 'dz', position: 'Forward' },
  { name: 'Islam Slimani', country: 'Algeria', flag: 'dz', position: 'Forward' },
  { name: 'Saïd Benrahma', country: 'Algeria', flag: 'dz', position: 'Midfielder' },
  { name: 'Ismaël Bennacer', country: 'Algeria', flag: 'dz', position: 'Midfielder' },
  { name: 'Youcef Atal', country: 'Algeria', flag: 'dz', position: 'Defender' },
  { name: 'Djamel Benlamri', country: 'Algeria', flag: 'dz', position: 'Defender' },
  { name: 'Anis Hammouchi', country: 'Algeria', flag: 'dz', position: 'Forward' },

  // ======================== COLOMBIA ========================
  { name: 'James Rodríguez', country: 'Colombia', flag: 'co', position: 'Midfielder' },
  { name: 'Luis Díaz', country: 'Colombia', flag: 'co', position: 'Forward' },
  { name: 'Jhon Córdoba', country: 'Colombia', flag: 'co', position: 'Forward' },
  { name: 'Rafael Santos Borré', country: 'Colombia', flag: 'co', position: 'Forward' },
  { name: 'Juan Cuadrado', country: 'Colombia', flag: 'co', position: 'Midfielder' },
  { name: 'Jefferson Lerma', country: 'Colombia', flag: 'co', position: 'Midfielder' },
  { name: 'Davinson Sánchez', country: 'Colombia', flag: 'co', position: 'Defender' },
  { name: 'Yerry Mina', country: 'Colombia', flag: 'co', position: 'Defender' },
  { name: 'David Ospina', country: 'Colombia', flag: 'co', position: 'Goalkeeper' },
  { name: 'Richard Ríos', country: 'Colombia', flag: 'co', position: 'Midfielder' },

  // ======================== SCOTLAND ========================
  { name: 'Scott McTominay', country: 'Scotland', flag: 'gb-sct', position: 'Midfielder' },
  { name: 'Andrew Robertson', country: 'Scotland', flag: 'gb-sct', position: 'Defender' },
  { name: 'John McGinn', country: 'Scotland', flag: 'gb-sct', position: 'Midfielder' },
  { name: 'Ryan Christie', country: 'Scotland', flag: 'gb-sct', position: 'Midfielder' },
  { name: 'Callum McGregor', country: 'Scotland', flag: 'gb-sct', position: 'Midfielder' },
  { name: 'Lawrence Shankland', country: 'Scotland', flag: 'gb-sct', position: 'Forward' },
  { name: 'Che Adams', country: 'Scotland', flag: 'gb-sct', position: 'Forward' },
  { name: 'Ryan Porteous', country: 'Scotland', flag: 'gb-sct', position: 'Defender' },
  { name: 'Angus Gunn', country: 'Scotland', flag: 'gb-sct', position: 'Goalkeeper' },
  { name: 'Grant Hanley', country: 'Scotland', flag: 'gb-sct', position: 'Defender' },

  // ======================== SWITZERLAND ========================
  { name: 'Granit Xhaka', country: 'Switzerland', flag: 'ch', position: 'Midfielder' },
  { name: 'Xherdan Shaqiri', country: 'Switzerland', flag: 'ch', position: 'Midfielder' },
  { name: 'Breel Embolo', country: 'Switzerland', flag: 'ch', position: 'Forward' },
  { name: 'Noah Okafor', country: 'Switzerland', flag: 'ch', position: 'Forward' },
  { name: 'Dan Ndoye', country: 'Switzerland', flag: 'ch', position: 'Forward' },
  { name: 'Zeki Amdouni', country: 'Switzerland', flag: 'ch', position: 'Forward' },
  { name: 'Manuel Akanji', country: 'Switzerland', flag: 'ch', position: 'Defender' },
  { name: 'Gregor Kobel', country: 'Switzerland', flag: 'ch', position: 'Goalkeeper' },
  { name: 'Remo Freuler', country: 'Switzerland', flag: 'ch', position: 'Midfielder' },
  { name: 'Ardon Jashari', country: 'Switzerland', flag: 'ch', position: 'Midfielder' },
  { name: 'Rubén Vargas', country: 'Switzerland', flag: 'ch', position: 'Forward' },
  { name: 'Nico Elvedi', country: 'Switzerland', flag: 'ch', position: 'Defender' },

  // ======================== JAPAN ========================
  { name: 'Takumi Minamino', country: 'Japan', flag: 'jp', position: 'Forward' },
  { name: 'Ritsu Doan', country: 'Japan', flag: 'jp', position: 'Forward' },
  { name: 'Daichi Kamada', country: 'Japan', flag: 'jp', position: 'Midfielder' },
  { name: 'Wataru Endo', country: 'Japan', flag: 'jp', position: 'Midfielder' },
  { name: 'Hidemasa Morita', country: 'Japan', flag: 'jp', position: 'Midfielder' },
  { name: 'Shuichi Gonda', country: 'Japan', flag: 'jp', position: 'Goalkeeper' },
  { name: 'Maya Yoshida', country: 'Japan', flag: 'jp', position: 'Defender' },
  { name: 'Takehiro Tomiyasu', country: 'Japan', flag: 'jp', position: 'Defender' },
  { name: 'Kaoru Mitoma', country: 'Japan', flag: 'jp', position: 'Forward' },
  { name: 'Ao Tanaka', country: 'Japan', flag: 'jp', position: 'Midfielder' },

  // ======================== SOUTH KOREA ========================
  { name: 'Son Heung-min', country: 'South Korea', flag: 'kr', position: 'Forward' },
  { name: 'Lee Kang-in', country: 'South Korea', flag: 'kr', position: 'Midfielder' },
  { name: 'Kim Min-jae', country: 'South Korea', flag: 'kr', position: 'Defender' },
  { name: 'Hwang Hee-chan', country: 'South Korea', flag: 'kr', position: 'Forward' },
  { name: 'Hwang In-beom', country: 'South Korea', flag: 'kr', position: 'Midfielder' },
  { name: 'Jo Hyun-woo', country: 'South Korea', flag: 'kr', position: 'Goalkeeper' },
  { name: 'Yang Hyun-jun', country: 'South Korea', flag: 'kr', position: 'Midfielder' },
  { name: 'Cho Kyu-sung', country: 'South Korea', flag: 'kr', position: 'Forward' },
  { name: 'Oh Hyun-kyu', country: 'South Korea', flag: 'kr', position: 'Forward' },

  // ======================== SWEDEN ========================
  { name: 'Viktor Gyökeres', country: 'Sweden', flag: 'se', position: 'Forward' },
  { name: 'Dejan Kulusevski', country: 'Sweden', flag: 'se', position: 'Midfielder' },
  { name: 'Alexander Isak', country: 'Sweden', flag: 'se', position: 'Forward' },
  { name: 'Emil Forsberg', country: 'Sweden', flag: 'se', position: 'Midfielder' },
  { name: 'Robin Olsen', country: 'Sweden', flag: 'se', position: 'Goalkeeper' },
  { name: 'Victor Lindelöf', country: 'Sweden', flag: 'se', position: 'Defender' },
  { name: 'Ludwig Augustinsson', country: 'Sweden', flag: 'se', position: 'Defender' },
  { name: 'Mattias Svanberg', country: 'Sweden', flag: 'se', position: 'Midfielder' },

  // ======================== IVORY COAST ========================
  { name: 'Sébastien Haller', country: 'Ivory Coast', flag: 'ci', position: 'Forward' },
  { name: 'Nicolas Pépé', country: 'Ivory Coast', flag: 'ci', position: 'Forward' },
  { name: 'Franck Kessié', country: 'Ivory Coast', flag: 'ci', position: 'Midfielder' },
  { name: 'Jean-Philippe Gbamin', country: 'Ivory Coast', flag: 'ci', position: 'Midfielder' },
  { name: 'Serge Aurier', country: 'Ivory Coast', flag: 'ci', position: 'Defender' },
  { name: 'Eric Bailly', country: 'Ivory Coast', flag: 'ci', position: 'Defender' },
  { name: 'Simon Adingra', country: 'Ivory Coast', flag: 'ci', position: 'Forward' },
  { name: 'Oumar Diakité', country: 'Ivory Coast', flag: 'ci', position: 'Midfielder' },

  // ======================== BOSNIA & HERZEGOVINA ========================
  { name: 'Edin Džeko', country: 'Bosnia', flag: 'ba', position: 'Forward' },
  { name: 'Ermedin Demirović', country: 'Bosnia', flag: 'ba', position: 'Forward' },
  { name: 'Miralem Pjanić', country: 'Bosnia', flag: 'ba', position: 'Midfielder' },
  { name: 'Sead Kolašinac', country: 'Bosnia', flag: 'ba', position: 'Defender' },
  { name: 'Nikola Vasilj', country: 'Bosnia', flag: 'ba', position: 'Goalkeeper' },
  { name: 'Benjamin Tahirović', country: 'Bosnia', flag: 'ba', position: 'Midfielder' },
  { name: 'Amar Dedić', country: 'Bosnia', flag: 'ba', position: 'Defender' },
  { name: 'Haris Tabaković', country: 'Bosnia', flag: 'ba', position: 'Forward' },

  // ======================== PANAMA ========================
  { name: 'Rolando Blackburn', country: 'Panama', flag: 'pa', position: 'Forward' },
  { name: 'Ismael Díaz', country: 'Panama', flag: 'pa', position: 'Forward' },
  { name: 'Édgar Bárcenas', country: 'Panama', flag: 'pa', position: 'Midfielder' },
  { name: 'Adalberto Carrasquilla', country: 'Panama', flag: 'pa', position: 'Midfielder' },
  { name: 'Rodrigo Schlegel', country: 'Panama', flag: 'pa', position: 'Defender' },
  { name: 'Luis Mejía', country: 'Panama', flag: 'pa', position: 'Goalkeeper' },
  { name: 'Cecilio Waterman', country: 'Panama', flag: 'pa', position: 'Forward' },

  // ======================== SOUTH AFRICA ========================
  { name: 'Percy Tau', country: 'South Africa', flag: 'za', position: 'Forward' },
  { name: 'Bongani Zungu', country: 'South Africa', flag: 'za', position: 'Midfielder' },
  { name: 'Themba Zwane', country: 'South Africa', flag: 'za', position: 'Midfielder' },
  { name: 'Ronwen Williams', country: 'South Africa', flag: 'za', position: 'Goalkeeper' },
  { name: 'Rushine De Reuck', country: 'South Africa', flag: 'za', position: 'Defender' },
  { name: 'Luther Singh', country: 'South Africa', flag: 'za', position: 'Forward' },

  // ======================== TUNISIA ========================
  { name: 'Wahbi Khazri', country: 'Tunisia', flag: 'tn', position: 'Forward' },
  { name: 'Youssef Msakni', country: 'Tunisia', flag: 'tn', position: 'Forward' },
  { name: 'Ellyes Skhiri', country: 'Tunisia', flag: 'tn', position: 'Midfielder' },
  { name: 'Aïssa Laïdouni', country: 'Tunisia', flag: 'tn', position: 'Midfielder' },
  { name: 'Montassar Talbi', country: 'Tunisia', flag: 'tn', position: 'Defender' },
  { name: 'Aymen Dahmen', country: 'Tunisia', flag: 'tn', position: 'Goalkeeper' },

  // ======================== DR CONGO ========================
  { name: 'Yoane Wissa', country: 'DR Congo', flag: 'cd', position: 'Forward' },
  { name: 'Aaron Wan-Bissaka', country: 'DR Congo', flag: 'cd', position: 'Defender' },
  { name: 'Théo Bongonda', country: 'DR Congo', flag: 'cd', position: 'Forward' },
  { name: 'Cédric Bakambu', country: 'DR Congo', flag: 'cd', position: 'Forward' },
  { name: 'Chancel Mbemba', country: 'DR Congo', flag: 'cd', position: 'Defender' },
  { name: 'Arthur Masuaku', country: 'DR Congo', flag: 'cd', position: 'Defender' },
  { name: 'Joris Kayembe', country: 'DR Congo', flag: 'cd', position: 'Midfielder' },

  // ======================== HAITI ========================
  { name: 'Jean-Ricner Bellegarde', country: 'Haiti', flag: 'ht', position: 'Midfielder' },
  { name: 'Frantzdy Pierrot', country: 'Haiti', flag: 'ht', position: 'Forward' },
  { name: 'Duckens Nazon', country: 'Haiti', flag: 'ht', position: 'Forward' },
  { name: 'Johny Placide', country: 'Haiti', flag: 'ht', position: 'Goalkeeper' },
  { name: 'Steeven Saba', country: 'Haiti', flag: 'ht', position: 'Forward' },

  // ======================== CURACAO ========================
  { name: 'Leandro Bacuna', country: 'Curacao', flag: 'cw', position: 'Midfielder' },
  { name: 'Juninho Bacuna', country: 'Curacao', flag: 'cw', position: 'Midfielder' },
  { name: 'Cuco Martina', country: 'Curacao', flag: 'cw', position: 'Defender' },
  { name: 'Rangelo Janga', country: 'Curacao', flag: 'cw', position: 'Forward' },
  { name: 'Kevin Felida', country: 'Curacao', flag: 'cw', position: 'Midfielder' },

  // ======================== QATAR ========================
  { name: 'Akram Afif', country: 'Qatar', flag: 'qa', position: 'Forward' },
  { name: 'Almoez Ali', country: 'Qatar', flag: 'qa', position: 'Forward' },
  { name: 'Hassan Al-Haydos', country: 'Qatar', flag: 'qa', position: 'Midfielder' },
  { name: 'Mohammed Muntari', country: 'Qatar', flag: 'qa', position: 'Forward' },
  { name: 'Meshaal Barsham', country: 'Qatar', flag: 'qa', position: 'Goalkeeper' },
  { name: 'Karim Boudiaf', country: 'Qatar', flag: 'qa', position: 'Midfielder' },
  { name: 'Pedro Miguel', country: 'Qatar', flag: 'qa', position: 'Defender' },

]

export default PLAYERS